### ISSUE TITLE
[Use Case] Save Remix contract

### ISSUE THREAD

**Issue by GrandSchtroumpf** [3box/3box-js#102]
I'm working on a plugin for remix and I'm thinking of using `3box-js`.
Would it make sense to store your contract on remix inside your 3box profile?
Something like : 
```javascript
// contractList is an array of string
box.public.set('remix', JSON.stringify(contractList));
```

**Comment by oed** [comment]
Sounds cool. Yeah I see no problem with this 🙂 What would be in the `contractList` object?

**Comment by GrandSchtroumpf** [comment]
My plugin computes a documentation object per contract. So it can either be the code of the contract or the full documentation object, depending on the size limit if any.

**Comment by oed** [comment]
We don't currently have any limitation. But keep in mind that openBox will become slower over time as you add more data. Currently at least, in the future we plan to add efficiency improvements to mitigate this limitation. Also note that we might start limiting data usage by dapps in the future, it's still undecided how that will work yet though.

**Comment by joaoaguiam** [comment]
Hey, in order to avoid that heavy data being sent to 3box profile directly, why not pushing it to the IPFS and then just store the hash on the profile? 

I am not completely aware of the limitation on 3box but this seems a good trade-off.

**Comment by oed** [comment]
@joaoaguiam Yes, that seems like a good trade off for now :)

**Comment by GrandSchtroumpf** [comment]
Well, I thought that the 3box profile was hosted on OrbitDB which is built on top of IPFS. So would it not be the same in the end ?

**Comment by oed** [comment]
@GrandSchtroumpf sure, both would be on ipfs. But this way you could use another ipfs node to pin the large data e.g. INFURA.
