### ISSUE TITLE
Error: There is already a transport with this key

### ISSUE THREAD

**Issue by joaoaguiam** [3box/3box-js#110]
**Describe the bug**
When opening the box the following error occurs: "Error: There is already a transport with this key"

**To Reproduce**
1. Deploy version 1.0.0-beta-8
2. Open box 

**Screenshots**
<img width="1183" alt="screen shot 2018-10-10 at 19 06 34" src="https://user-images.githubusercontent.com/5901730/46774600-827fc980-ccc0-11e8-8dd3-f691ae6c0bc4.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by oed** [comment]
Ty, I'll try to reproduce this today!

**Comment by joaoaguiam** [comment]
Hi @oed , I tried to rollback to the version 1.0.0-beta-7 and the platform runs correctly. Error is only happening on version beta-8 and beta-9.

**Comment by oed** [comment]
This error has also been reported separately on our discord.

**Comment by oed** [comment]
This error is coming from ipfs, libp2p in particular. Still haven't been able to figure out why it happens, but it seems like it's only happening for some people when building their react projects. The dist builds provided by 3box-js are not affected by this. So while we try to figure out a solution for this problem you can use this workaround:

copy the 3box dist file to your `public` folder:
```
$ cp node_modules/3box/dist/3box.min.js public/
```
edit your `public/index.html` file, add the following inside of the `<head></head>` tags:
```html
<script src="./3box.js" type="text/javascript"></script>
```
Now the `ThreeBox` object should be globally available in your project.

**Comment by oed** [comment]
This error seems to be an issue with react-scripts not supporting ES6 (which ipfs uses). See this comment for how to address it: https://github.com/uport-project/3box-js/issues/134#issuecomment-432486308

**Comment by oed** [comment]
@joaoaguiam when you get around to, can you try out this solution and see if it works: https://github.com/3box/3box-dapp/issues/238#issuecomment-454878398

**Comment by oed** [comment]
I believe this error is no longer around. Please repopen if you see it surfacing again :)
