### ISSUE TITLE
Thought/Suggestion - Official dApp reserved keys + official dApp specific methods (maybe)

### ISSUE THREAD

**Issue by rej156** [3box/3box-js#121]
box.officialDapps["dAppReservedKey"].preDefinedSetterOrGetter
e.g. box.officialDapps.kudos.giveKudos("Kauri", {name: "", avatar: ""})

Although predefined setters and getters would involve multiple PRs from those dApps against the 3box-js repo if those setters or getters get updated in any way.
Hence the maybe about the latter thought!

**Comment by rej156** [comment]
Maybe the dApp maintainers could provide validators against specific setter keys?
e.g. ...kudos.set("giveKudos", value) calls a validation prehook function to make sure value is passed a proper type or shape that matches their required dApp spec

**Comment by oed** [comment]
Thanks @rej156 I think this makes sense. We've had a similar idea of adding "namespaces" which would essentially be additional orbit-db stores. This would pretty much allow for what you are asking for without requiring devs to make PRs to 3box. Have a look at how to make orbit-db-stores [here](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#custom-stores). 

We could have an additional interface for creating/opening these custom stores, something like:
##### box.createNamespace(name, type, [customStore])

##### box.openNamespace(name, type, [customstore])

**Comment by rej156** [comment]
Yass please!

Could adapt https://github.com/Stradivario/gapi-orbitdb/tree/master to provide a graphql framework for dApps to create an interface around those custom stores

**Comment by oed** [comment]
@rej156 This is now mostly addressed by [Spaces](https://github.com/3box/3box/blob/8342898f37454998bbc47b8df593046417189ec9/specs/spaces-implementation.md)? 
There is no custom getters/setters though, but that would be hard to generalize in a secure way without dapp devs having to make PRs to the 3box repo. It might also be confusing to new devs.

Closing for now. Please reopen if you have any additional questions.
