### ISSUE TITLE
Feature Request: Offer LinniaJS capabilities in 3Box.js

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-js#129]
Just had a call with @davidrhodus and we spoke about potentially offering the [LinniaJS](https://github.com/ConsenSys/linnia-js) smart contract access control capability within the 3Box system. Wanted to create a ticket to hold the conversations about what would be needed for this to be a viable option. Anything to add David or @zachferland?

The user story might be something like: 'As a 3box user I want to be able to offer individual pieces of my data for sale.'

For consideration.

**Comment by oed** [comment]
Interesting, we could maybe add a separate namespace with individually encrypted data pieces that are up for sale? Need to learn more about how Linnia works though.
