### ISSUE TITLE
Add dist into a CDN

### ISSUE THREAD

**Issue by GrandSchtroumpf** [3box/3box-js#167]
Could you add the dist folder into a CDN for people who don't want to use npm?
Thanks

**Comment by zachferland** [comment]
@GrandSchtroumpf it is already available on unpkg at `https://unpkg.com/3box@1.0.4/dist/3box.js`, but we will add a note in the readme as well

**Comment by oed** [comment]
@z

**Comment by zachferland** [comment]
Resolved with https://github.com/3box/3box-js/pull/201, closing now
