### ISSUE TITLE
Save account creation event to log

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-js#191]

**Comment by oed** [comment]
Why is this needed? Can't we just look at the time of the first entry in either the public or the private store?

**Comment by zachferland** [comment]
Yeah I don't know if account creation is meaningful before the time there is at least one entry, we discussed a bit yesterday. Sounds like it might be useful for ui stuff in the dapp, but in that case we mentioned if might sense for the dapp instead of the lib to add something. Have to follow up once we get to it

**Comment by oed** [comment]
@michaelsena @oznekenzo Maybe you could clarify a bit here?

**Comment by michaelsena** [comment]
Yup @oed I want to implement a "member since" feature on the platform, since I think it can become a strong proof of identity in the future. "I am the real Michael Sena because I've been a 3Box member since October 2018."

**Comment by oed** [comment]
@michaelsena but can't we already do this by taking the date of the first entry in your profile?

**Comment by oznekenzo** [comment]
@oed Yeah that's possible of course, but if a user creates an account but doesn't write to it, he won't have a member-start date

**Comment by oznekenzo** [comment]
But we can use that hack in the meantime @oed

**Comment by oed** [comment]
I wouldn't really say that a user that has not added any data to their profile has created an account. So I don't really see this as an issue :)

**Comment by michaelsena** [comment]
‘Member since’ in the dapp should reflect when the user first logged into 3Box.io. 

I’d say first login to 3Box.io is when a user thinks they created their 3Box.io account, even if they didn’t add data to their profile during that session. That’s how twitter and every other app work. 

And this is different from when the user creates their 3Box, which could be done at another app behind the scenes.

**Comment by oed** [comment]
Ok, in that case this is just an entry that can be added by the dapp.

**Comment by michaelsena** [comment]
Should we move this issue to 3box-dapp?

**Comment by oed** [comment]
Yeah :)

**Comment by michaelsena** [comment]
But separately, we should probably also store an event when the 3Box is created, which should likely be done by js — thoughts?

**Comment by oed** [comment]
I don't see very much utility of that from a user perspective.

**Comment by zachferland** [comment]
Can this story be closed?
