### ISSUE TITLE
Error: Cannot find module 'uglifyjs-webpack-plugin' when running example

### ISSUE THREAD

**Issue by cloudonshore** [3box/3box-js#194]
**Describe the bug**

After running `yarn`, and running `npm run example:start`, I get the following error:
`Error: Cannot find module 'uglifyjs-webpack-plugin'`

After running `yarn add uglifyjs-webpack-plugin` it works correctly, the package most likely just needs to be added to the dev dependencies. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by oed** [comment]
Hey @cloudonshore, thanks for reporting! 
I just did a clean install of this repo and ran `npm install` then `npm run example:start` which worked fine. Are you sure that this isn't just a problem with `yarn`?

**Comment by zachferland** [comment]
Added uglifyjs-webpack-plugin as dev dependency, since we do include it in the webpack config, worked without it in npm, but should be explicitly added anyways. https://github.com/3box/3box-js/pull/208 Thanks @cloudonshore!
