### ISSUE TITLE
Stores not instantly replicating and sharing updates

### ISSUE THREAD

**Issue by zachferland** [3box/3box-js#203]
App1 makes write, load App 2, App2 doesn't receive new entry.
Then reload App 1, load App2, now App2 has received the update.

There is an error connecting to a libp2p bootstrap node, but may or may not be related to this issue. As this is a process that happens in the background as it looks for peers. Although this issue I don't think was seen until this libp2p error was seen.

It appears updates are only be sent (from local store) on library load. Could be another issues or if related to libp2p bootstrap issue, could be error thrown in libp2p is blocking other libp2 processes. So it works on load since those updates are sent before the libp2p error I thrown. 

This issue was reported by @oznekenzo and on discord last week

**Comment by zachferland** [comment]
discussed in standup, but yeah exactly, thats a more succinct way to put it. So works on start until some failure comes along. As mentioned, have not confirmed this using a local instance of the pinning-node yet. Leaving this issue open until we can confirm bootstrap configs can prevent this issue or it has to be pinpointed further.

**Comment by oed** [comment]
This is still in **code review**. @zachferland Do you have an update?

**Comment by zachferland** [comment]
Going to close for now, have not replicated the same issue lately, and two many fixes have have between then and now that is not possible to attribute to any of the options listed in this issue.
