### ISSUE TITLE
Changing data in dapp triggers requests to create new profile 

### ISSUE THREAD

**Issue by dazuck** [3box/3box-js#205]
**Describe the bug**
When using 3box.io to edit my profile, after I saved the new data I had a popup from metamask asking me to sign a transaction. The message in the transaction indicated it was to create a new profile (see screenshot) 

It appears (from metamask notifications) that 1 signature request was triggered for each piece of data changed? 

data was saved to 3box profile even though I declined transaction. 

![image](https://user-images.githubusercontent.com/8866608/49412267-d4315700-f739-11e8-89c3-828a5dbef8d5.png)

**Desktop (please complete the following information):**
Chrome + Metamask

**Comment by dazuck** [comment]
update: nvm, data is gone when I come back a couple hours later.

**Comment by oed** [comment]
@dazuck this should only happen once. Can you elaborate on when exactly this happened in the flow?
What do you mean by "data is gone"?

**Comment by dazuck** [comment]
As soon as I clicked "Save" in the dapp, the consent messages were triggered. 
When i log back into the dapp, the data I had previously entered and saved (or tried to, and it looked saved) are not showing up in my profile. all fields are reset to blank.

**Comment by oed** [comment]
Strange, you did not reset you cache or anything either right?
@zachferland could this be related to the connection issue maybe?

**Comment by oed** [comment]
Stale, closing.
