### ISSUE TITLE
Optimize getProfile

### ISSUE THREAD

**Issue by oed** [3box/3box-js#217]
Make sure that:
- [ ] global ipfs & orbitdb objects works as intended, are they still needed when we use the iframe?
- [x] loading a profile works with & without cache

Are there other cleanups and optimizations that we can do? (take a while to read code thoroughly and investigate)

**Comment by oed** [comment]
Not sure if there is much we can do here right now. My main concern with global ipfs & orbitdb was that if you do multiple getProfiles and there is no global ones we might run into trouble with there being multiple instances. However I don't think this is much of a problem now that we have the caching layer.

I would like to refactor all of the orbitdb stuff a bit, but I think it's fine for now. Moving this to review column. 
cc @zachferland

**Comment by zachferland** [comment]
Yup agree, doesn't require attention now, and can be part of a refactor of orbit db stuff in the future.
