### ISSUE TITLE
Bug: Listener function not available error thrown after openbox loads when using iframe 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-js#222]
Some issue with using the ipfs proxy. The ipfs proxy doesn't seem to work for events/listeners, probably some to do with the callbacks, they can't be encoded for postmessage, and since dev provided callback it can't be sure that those arguments are encodable (could be func args) and in that case it just can't encode it. 

Think mentioned elsewhere, but a better solution to the ipfs proxy, may be to just create an ipfs data proxy instead of wrapping the entire ipfs lib. Probably with less api surface area, we will run into less of these issues.

**Comment by oed** [comment]
Stale, closing.
