### ISSUE TITLE
Support both eth-addr and muport-did in getProfile

### ISSUE THREAD

**Issue by oed** [3box/3box-js#226]
Currently we only support getting profiles by ethereum address. We need to support getting them with a muport DID also.

Also update documentation for this.

**Comment by oed** [comment]
We should also support it in the other API functions.

**Comment by lsenta** [comment]
Do we want to support `getProfile(did:muport)` when the API / cache is disabled?

**Comment by oed** [comment]
I think let's skip the support for DID when API is disabled. Afaik not many people use that since it's kind of slow.
Also note that we should add support for DIDs in `getSpace` and `listSpaces` as well.

**Comment by lsenta** [comment]
@oed Does it makes sense to support getProfiles too?

**Comment by oed** [comment]
oh, yes of course!
