### ISSUE TITLE
Use new graphql endpoint

### ISSUE THREAD

**Issue by oed** [3box/3box-js#247]

**Comment by oed** [comment]
Also use the new cache endpoint.

**Comment by lsenta** [comment]
The new cache endpoint is not yet active, correct?

**Comment by oed** [comment]
The new endpoint for graphql should be `api.3box.io/graph/`, which should be active. [See here for reference](https://github.com/3box/3box/blob/master/devops/service-endpoints.md#3box-graphql)

**Comment by lsenta** [comment]
I was referring to your comment:

> Also use the new cache endpoint.

**Comment by oed** [comment]
Oh, sorry. I though it was active actually. Is that not the case?

**Comment by lsenta** [comment]
Nope

**Comment by oed** [comment]
ok, let's just do the graphql endpoint then :)
