### ISSUE TITLE
Calling getprofile returns the error "utils.fetchJson is not a function"

### ISSUE THREAD

**Issue by Akaryatrh** [3box/3box-js#248]
**Describe the bug**
A simple `await Box.getProfile('0x0c269b2d1376b2a2a5222564f9c8ea0065dd2c79');` will return an error saying `utils.fetchJson is not a function`

Bug is quite simple : npm package contains a `utils.js` file along a `/utils` folder. Webpack will use the file when importing module, but won't find the `fetchJson()` function.
The `utils.js` file should not be there.

**To Reproduce**
1. Install package 3box `v1.1.0`
2. Try to get a profile with `Box.getProfile()` method
4. Error pops-in console

**Comment by oed** [comment]
Thanks for reporting! Will have a fix in the next version! (which will be released today)

**Comment by sethfork** [comment]
Submitted a PR with a fix. Let me know if you'd like me to change anything @oed

**Comment by c-castillo** [comment]
Hi @sethfork! Thanks for the PR, however your fix is already done in release 1.2.0 (source file https://github.com/3box/3box-js/blob/develop/src/utils/index.js)
I'll close this PR for now since it's a duplicate.

Thanks again!
