### ISSUE TITLE
Update linkProfile logic

### ISSUE THREAD

**Issue by oed** [3box/3box-js#257]
The "linkProfile" logic is due for an update. Things that should be addressed:
- [ ] Move logic for linking profile into the 3id module
- [ ] Stop using localstorage, since the link is stored in the 3box anyway
- [ ] Move the logic to happen during the same time as `_ensureDIDPublished`. There is no need to check it every time a new entry is added to the public profile.

**Comment by michaelsena** [comment]
@lsenta please ping @oed for more details when you get to this one!

**Comment by lsenta** [comment]
Regarding `Stop using localstorage, since the link is stored in the 3box anyway`:

we store the link in the 3box but we do not store the information that the link was published to the address server. https://github.com/3box/3box-js/blob/develop/src/3box.js#L401
Should I store this info in the public space of the 3box?

**Comment by oed** [comment]
@lsenta I don't think that is needed. It doesn't really matter if it's published multiple times to the address-server. So we can just continue doing that until we fold the address-server into the pinning-node at which point no http requests should be needed.

**Comment by lsenta** [comment]
Sounds good,
can you give me more insight on why move the logic into the 3id module? And what's the features / intent of the 3id module?

Right now, `_linkProfile` combines a few did calls, API calls and 3box storage calls. It seems logical, to me, that it stays in the 3box module.
https://github.com/3box/3box-js/blob/09a1202f143991a953b4db9f7bb0814b9975d437/src/3box.js#L383-L412

**Comment by oed** [comment]
Ah, yes I think you are right @lsenta!
