### ISSUE TITLE
when trying to getVerifiedAccounts on a profile created before 1.2.0 we get an error

### ISSUE THREAD

**Issue by tzapu** [3box/3box-js#258]
**Describe the bug**
When calling `Box.getVerifiedAccounts(profile)` on a profile created before 3box 1.2.0 that has no twitter/github identities, we get back an error `no JWT passed into decodeJWT`
![screenshot 2019-01-16 12 16 46](https://user-images.githubusercontent.com/2983312/51242424-9eae9900-1988-11e9-990b-c22312a1c0ff.png)

**To Reproduce**
1. Go to 'https://jsfiddle.net/gnt39L2j/'
2.  Open Inspect/Console
3. Check out the error

**Expected behavior**
Not to error

**Screenshots**
![screenshot 2019-01-16 12 16 46](https://user-images.githubusercontent.com/2983312/51242439-a8d09780-1988-11e9-8949-75c144284370.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome, safari
**Additional context**
Spoke on discord with @oed

**Comment by oed** [comment]
This is because we assume that there is a `proof_did` property in `getVerifiedAccounts`

**Comment by tzapu** [comment]
is there a release planned that includes this fix as well?

thanks for the super prompt response with this issue

**Comment by oed** [comment]
@tzapu 1.2.1 is now released :) https://github.com/3box/3box-js/releases

**Comment by tzapu** [comment]
just wanted to confirm that this has sorted it.
