### ISSUE TITLE
Second onSyncDone doesn't call

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-js#261]
How to replicate: Arrive at dapp -> sign in and openBox -> onSyncDone -> sign out -> sign in again and openBox -> no onSyncDone

**Comment by oznekenzo** [comment]
Behavior:

Arrive at dapp -> sign in and openBox -> onSyncDone -> sign out -> sign in again and openBox -> no onSyncDone

**Comment by zachferland** [comment]
Was able to replicate 👍  Only happens when not reloading page and following steps above. Not a frequent use case, and logically the data would already be there, no need for on sync done, but of course expected openbox functionality should always bet he same, so we will get a fix for this.
