### ISSUE TITLE
Update to ipfs 0.34

### ISSUE THREAD

**Issue by oed** [3box/3box-js#276]
This build of ipfs should be somewhat smaller.
Hopefully updating shouldn't cause to many issues!

**Comment by michaelsena** [comment]
Investigate that this isn't too much work.

**Comment by zachferland** [comment]
has orbit update now as well?

**Comment by oed** [comment]
@zachferland good point. They mentioned it during their community call. Looks like we'll have to wait for a while before we can do this: https://github.com/orbitdb/orbit-db/issues/543#issuecomment-454749224
Removing this story from sprint 13 for now.

**Comment by oed** [comment]
Moving this to sprint 19 since we will update to the new orbitdb version.

**Comment by oed** [comment]
Maybe we can just use 0.35.0?

**Comment by zachferland** [comment]
Maybe, not sure yet, but orbit is on 0.34.0 in the new release

**Comment by zachferland** [comment]
Production build size 3.8mb to 2.7mb so far (about ~30% decrease).

**Comment by zachferland** [comment]
Could close this story for now if just for 3box-js. Anything remaining would just be related to orbitdb upgrade. On the pinning node side though, should confirm everything works there as expected, been tested locally. But also need to confirm changes like s3 data store/repo also still work as expected.

**Comment by oed** [comment]
Let's move this to staging for now, then create new stories for the pinning-node. We can close this once we've created new stories there.
