### ISSUE TITLE
Investigate other potential build size reductions

### ISSUE THREAD

**Issue by oed** [3box/3box-js#277]
If we can find other low hanging fruit, that are low effort, high impact.

**Comment by zachferland** [comment]
Low effort option for many use cases, separate "read/write" modules and use es6 modules, reads being getProfile and graphql. Then you can `import { getProfile } from '3box'` and it will probably include less than 100kb vs all 3-4mb needed to for ipfs/orbit. So at least read only uses case like alethio will be very minimal overhead.

**Comment by oed** [comment]
Yes right, forgot about this. Thanks @zachferland. Do you mind creating a story for it?

**Comment by zachferland** [comment]
yup creating a story now

**Comment by oed** [comment]
@zachferland Do you have any other ideas for this currently? Otherwise I think we can close this for now.

**Comment by zachferland** [comment]
No more at the moment, the es6 modules are related, but they only reduced by about 100mb and are already captured in a PR. agree, lets close :+1:

**Comment by oed** [comment]
100mb sound pretty good 😂

**Comment by zachferland** [comment]
well sounds better as it gets smaller haha, not so much when it was 4/5mb. Also think the same could be done with require, so the es6 switch wasn't super valuable, but we will see.
