### ISSUE TITLE
getProfile returning empty object

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#283]
<img width="1113" alt="screen shot 2019-01-23 at 1 51 15 pm" src="https://user-images.githubusercontent.com/8059373/51629933-d2ed0100-1f16-11e9-987c-9a0627ab1f65.png">

**Comment by oed** [comment]
@zachferland can this issue be closed?

**Comment by oed** [comment]
This issue has been fixed, thanks for reporting :)
