### ISSUE TITLE
Write copy for space consent message

### ISSUE THREAD

**Issue by oed** [3box/3box-js#285]
Just realized that we didn't have a story for this. Outcome of this story should be a text that is displayed to the user when they are asked to sign the consent for a space that is being opened. It must include the name of the space.

**Comment by oed** [comment]
Placeholder is `This app wants to view and update your 3Box space ${name}.`
I think your suggestion could work. Can we try it out with a few different names to see if something weird happens?

**Comment by michaelsena** [comment]
@oed awaiting your review here. Seems good to me with the examples above.
