### ISSUE TITLE
getVerifiedAccounts should also return the DID of the user

### ISSUE THREAD

**Issue by oed** [3box/3box-js#295]
Right now there is no good way to get the DID of a user you've called `getProfile` for. In the `getVerifiedAccounts` function the `proof_did` is verified, so we should include the DID as a result.

**Comment by lsenta** [comment]
Once we decode the did claim / JWT what do we want to send back to the user as part of the proof? The `did` and `issuer`?

**Comment by oed** [comment]
@lsenta We basically only need to send back the DID which is already verified in the code.

I changed this to a 3 (you can just change yourself next time), however this should be really simple. The DID is already verified in the [code](https://github.com/3box/3box-js/blob/develop/src/api.js#L67) we just need to add it to the `verifs` object like so: `verifs.did = did` 🙂

**Comment by lsenta** [comment]
Got it, I was looking for some symmetry: other verifications return an object with details about the proof:

```
- github: {username, proof}
- twitter: {username, proof, verifier}
- email: {address, verifier}
```

**Comment by oed** [comment]
Right, in those cases "proof" is a url that you can manually verify yourself, and verifier is the idenitty of the verifying entity.
