### ISSUE TITLE
CORS error when getting public profile of non-existing address

### ISSUE THREAD

**Issue by filips123** [3box/3box-js#300]
## Actual behavior

When the public profile of  non-existing address is required with `Box.getProfile`, there will be CORS error about accessing https://ipfs.3box.io/profile and missing `Access-Control-Allow-Origin` header.

## Expected behavior

This should not happen. Instead, there should be an error that the address doesn't exist.

## Reproducing

1. Create a simple HTML file with required 3Box bundle:
```html
<script src="https://unpkg.com/3box/dist/3box.js"></script>
```

2. Optionally serve this file with the local web server (it would be same with or without the server):
```bash
python3 -m http.server 80 # Python 3
php -S localhost:80 # PHP
```

3. Open this file in any browser (Firefox, Chrome) and open browser's JavaScript console. Try to get the public profile of some non-existing address:
```js
const profile = await Box.getProfile('0x12345abcde')
console.log(profile)
```

4. You will see errors.

## Logs

```
GET https://ipfs.3box.io/profile?address=0x12345abcde 404

localhost/:1 Access to fetch at 'https://ipfs.3box.io/profile?address=0x12345abcde' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Uncaught (in promise) TypeError: Failed to fetch TypeError: Failed to fetch
localhost/:1 Uncaught (in promise) TypeError: Failed to fetch
```

## Enviroment

* Operating system: Windows 10
* Browsers: Firefox and Chrome

**Comment by zachferland** [comment]
thanks @filips123 for the detailed bug report! I was able to recreate what you are describing, yeah it looks like we don't have the same headers set for 404 response as 200 response on our pinning server serving the profile requests. I'm going to close this story and then create and reference another on our 3box-pinning-server for the fix, thanks again
