### ISSUE TITLE
Accept DIDs in getProfile() to increase interoperability

### ISSUE THREAD

**Issue by deiu** [3box/3box-js#326]
Hi,

The current implementation of `Box.getProfile()` only supports ethereum addresses. To help drive adoption of 3box and also to make it more interoperable with more generic DID applications, it would be useful to at least use a `muport` DID.

The thing that's missing is just another level of indirection. For example, starting from my 3box DID (e.g. `did:muport:QmYiEMtYauiPrak1uPN8UV82wztgF9cgL4gkCMtDUxUbao`) I can extract the CID that gets dereferenced to an object containing the `managementKey: "0x350f72a69d5673e9e180ca04665d367c2ebe98da"`, which then can be directly passed to `getProfile().

**Comment by oed** [comment]
Hey @deiu great suggestion. I totally agree that this would be a great additional feature! 
I think this feature would make sense to implement in the pinning-server cache instead of the 3box-js library, but there are likely some small changes needed here as well. 
A sidenote about the muport DID is that you can also from the `signingKey` deterministically generate the orbitdb-address of the users 3Box rootStore.

**Comment by deiu** [comment]
If this can be done in the pinning-server then all the better, as the client should avoid doing extra requests (which may fail and require to be caught).

> A sidenote about the muport DID is that you can also from the `signingKey` deterministically generate the orbitdb-address of the users 3Box rootStore.

So you're saying the orbitdb-address is what makes the muport DID?

**Comment by oed** [comment]
> So you're saying the orbitdb-address is what makes the muport DID? Do you have any examples involving the signingKey like that?

The other way around 🙂 The muport DID makes the orbitdb-address.

**Comment by oed** [comment]
@deiu Got an update for you! We are working on enabling this and should have it available in one or two weeks :) 
See here: https://github.com/3box/3box-pinning-server/issues/98

**Comment by deiu** [comment]
Awesome, thanks a lot!

**Comment by oed** [comment]
@deiu A new version was just release that has this feature!
https://github.com/3box/3box-js/releases/tag/v1.6.0
