### ISSUE TITLE
getProfile should return an empty profile if ethAddress doesn't have a 3Box.

### ISSUE THREAD

**Issue by oed** [3box/3box-js#327]
Right now the `getProfile` function throws an error if there is a 404 response from the getProfile api. It should return an empty object instead if that happens.

**Comment by zachferland** [comment]
Change could be breaking for some people, if relied in try/catch/reject to handle empty profiles, now would just return empty obj.

**Comment by oed** [comment]
Hm, good point. Not sure if it's a large concern though. Would most likely get the desired effect of not displaying any profile either way.

**Comment by zachferland** [comment]
Yeah not concerned really, just noting for future reference.

**Comment by michaelsena** [comment]
So does this mean we’ll make the change or not?

**Comment by lsenta** [comment]
A few details: right now we return an error object:

```js
{status: 'error', message: 'error details'}
```

(the code assumes the Fetch API throw when the HTTP Response is not 2xx, which is wrong)

I'm going to implement a patch to return an empty object, BUT the correct approach (long term) might be to spec our errors objects and throw something like a `ProfileNotFound`.

**Comment by lsenta** [comment]
Note: we're fixing the issue for others part of the API:

- _linkProfile => preserve behavior
- _publishRootStore => preserve behavior
- getRootStoreAddress => rethrow
- listSpaces => catch and return an empty array
- getSpace => catch and return an empty object
- getProfiles => rethrow (it's a list of profile so a "global" 404 error should be raised as an error).
- getProfile => empty profile
