### ISSUE TITLE
Add support for light clients

### ISSUE THREAD

**Issue by riusricardo** [3box/3box-js#329]
Most of 3box's interaction with the Ethereum blockchain could be done over light clients. It makes a lot of sense to interact interact with 3box profiles from IOT devices or mobile phones.

**Comment by oed** [comment]
@riusricardo for sure! Right now you can just pass in any ethereum provider to 3Box. This provider could be any type of node. So if I understand your question we already support light clients :)

**Comment by riusricardo** [comment]
@oed  You're right it should be already supported, thanks. I'll try another approach. I'm working with the parity's light.js lib.

**Comment by oed** [comment]
Ok great :) Closing this then!
