### ISSUE TITLE
Populate mock spaces data

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#340]

**Comment by oed** [comment]
@oznekenzo is this in the right repo? If so can you please provide some description of what it is that you want. Is it a feature request or something else? Not sure how it would be "devOps".

**Comment by oznekenzo** [comment]
@oed sorry no, was mean to be in the dapp.  Will move now

**Comment by oznekenzo** [comment]
Issue moved to [3box/3box-dapp #326](https://github.com/3box/3box-dapp/issues/326) via [**ZenHub**](https://www.zenhub.com/)
