### ISSUE TITLE
Add functions for checking and verifying claims

### ISSUE THREAD

**Issue by oed** [3box/3box-js#344]
We should provide an easier way to verify and check claims. This can be added as two simple functions:
* isClaim(<thing>) - returns a boolean which indicates if the thing is a claim
* verifyClaim(<claim>) - verifies the validity of the claim and returns the parsed data

We need to decide where it would be best to add these function in the api.

**Comment by michaelsena** [comment]
@oed figure out API! 😛

**Comment by oed** [comment]
Maybe we can do an identity utils module, similar to what @KamesCG described [here](https://github.com/3box/3box-js/issues/371). Something like:
```js
const { idUtils } = require('3box')
```

it would have the functions:
* `idUtils.isDID(<did>)` - checks if a string is a DID
* `idUtils.isClaim(<claim>)`- checks if a string is a JWT claim
*  `idUtils.verifyClaim(<claim>)`- verifies that a claim is valid and returns the parsed data.
