### ISSUE TITLE
Feature Request: DID Utilities Library

### ISSUE THREAD

**Issue by KamesCG** [3box/3box-js#371]
Would be nice to have a small little helper library to deal with DIDs.

Not sure if there is enough functions to require such a library, but for my first need is checking if a string is a muport DID.

```
const DID_MUPORT_PREFIX = 'did:muport:'
const isMuportDID = (address) => address.startsWith(DID_MUPORT_PREFIX)
```

Thank you.

**Comment by oed** [comment]
I think that makes sense, thanks for the suggestion @KamesCG! 
Maybe it would make sense to have this along with `isClaim` and `verifyClaim` functions (which verifies JWT claims)?
cc @lsenta

**Comment by lsenta** [comment]
Thanks for the feedbacks @KamesCG, the feature is complete, we're going to release it soon,
I'll let you know when it's live!

**Comment by lsenta** [comment]
@KamesCG we released the `idUtils` module and its documentation is available at: https://github.com/3box/3box-js#Box.idUtils

Don't hesitate to bump this ticket or let us know on discord if you have any questions!
