### ISSUE TITLE
Box.listSpaces sometimes returns empty array, should at least return error

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#377]
Even though there are spaces to which I belong, Box.listSpaces will return an empty array.  
Since we `getSpace` data from this list array, if the dapp gets an empty array from listSpaces, no data is rendered and since no error is returned, there's no way to know in the dapp whether to tell users to refresh the page.

**Comment by oed** [comment]
Does this always happen, or just sometimes? If only sometimes, under what conditions?

**Comment by zachferland** [comment]
Can't replicate the issues, based on info here, after many tries, i guess on hold for now. @oznekenzo please report again if you see this issue, especially if you can replicate.

**Comment by oznekenzo** [comment]
This happens for me very consistently. I will try to figure out the behavior that might be causing it, but really there doesn't seem to be a specific behavior, it just happens on dapp load.

**Comment by zachferland** [comment]
can you share the api call url?

**Comment by oznekenzo** [comment]
Sent to you now on discord

**Comment by oznekenzo** [comment]
<img width="608" alt="Screen Shot 2019-04-08 at 5 01 25 PM" src="https://user-images.githubusercontent.com/8059373/55756648-091f2480-5a20-11e9-94ec-7bd8043985b5.png">
<img width="411" alt="Screen Shot 2019-04-08 at 5 01 30 PM" src="https://user-images.githubusercontent.com/8059373/55756653-0cb2ab80-5a20-11e9-9b0c-65eab45c2e86.png">

**Comment by oznekenzo** [comment]
Still cannot discern any special kind of behavior.  
Happens about once every 30-50 loads?

**Comment by oed** [comment]
Any update on this @zachferland @oznekenzo ?

**Comment by michaelsena** [comment]
if we haven't replicated this in a ~week we will close this and assume it's solved by the new infra.

**Comment by michaelsena** [comment]
We think this is fixed, closing
