### ISSUE TITLE
3box dapp breaks when 3box public profile has a field with value `undefined`

### ISSUE THREAD

**Issue by Schwartz10** [3box/3box-js#401]
**Describe the bug**
If a user's public box has a field with with `undefined` for a value, the dapp seems to break.

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/12353734/56766118-af845d00-6776-11e9-84d9-786b1ecc8c91.png">

(not sure what the top errors are, see bottom two)

**To Reproduce**
Simply call `openedBox.public.set` with no values, then go to 3box.io and try to view your profile

**Expected behavior**
I think calling `openedBox.public.set` with no values should throw an error

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by oed** [comment]
@Schwartz10 A fix is implemented and should be ready for the next release! See #402
