### ISSUE TITLE
Add blocklist interface

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-js#432]
This is required for the Livepeer profiles integration.

Does this also need to happen on pinning node or just in client?

**Comment by oed** [comment]
A change is only needed on the client. I made a quick draft of what the interface would look like. 
https://hackmd.io/wkUCdElrQiGeVTgdjizlJg

**Comment by michaelsena** [comment]
Thanks for drafting @oed this is helpful. Let's see what the Livepeer team says
