### ISSUE TITLE
Box.getVerifiedAccounts does not return verified accounts

### ISSUE THREAD

**Issue by Schwartz10** [3box/3box-js#444]
**Describe the bug**
[`Box.getVerifiedAccounts`](https://github.com/3box/3box-js#boxgetverifiedaccountsprofile--object) does not return any of my verified accounts.

**To Reproduce**
Here's the code I'm using:

```js
  getVerifiedAccounts = async (ethereumAddress) => {
    const profile = await Box.getProfile(ethereumAddress)
    return Box.getVerifiedAccounts(profile)
  }
// returns {}
```

Yet I have a `proof_github` in the profile that is returned from `Box.getProfile`

**Expected behavior**

The verified accounts to be returned, with information about their proofs

**Desktop (please complete the following information):**
 - Chrome
 - Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by oed** [comment]
@Schwartz10 are you using v1.8.0 by any chance? Can you try updating to v1.8.1?

**Comment by Schwartz10** [comment]
It's working on 1.8.3! Closing.
