### ISSUE TITLE
Info saved in 3box dapp does not populated in Box.getProfile() call

### ISSUE THREAD

**Issue by Schwartz10** [3box/3box-js#453]
**Describe the bug**

**To Reproduce**
1. Create a new metamask account
2. Save your name on 3box 
3. go to another application of your own, running 3box-js
4. make the `Box.getProfile(ethAddress)` call
5. Profile comes back empty

I cycled through these steps a multiple times, which @zachferland suggested might fix the problem, still with no luck.

**Expected behavior**
Information set anywhere with 3box-js should populate to other applications running it

**Comment by oed** [comment]
Can you try fetching this from your browser?
`https://ipfs.3box.io/profile?address=<ethAddress>`
(This is what ´Box.getProfile` does internally). I cant seem to recreate this 🤔

**Comment by Schwartz10** [comment]
Ha! That works. Let me see if i can recreate again hang on

**Comment by Schwartz10** [comment]
Ok, doing this again, immediately I get:

```js
{

    "status": "error",
    "message": "Address link not found, address does not have a 3Box or is malformed"

}
```

**Comment by oed** [comment]
I assume that is with a new account? Does this happen each time or just randomly?

**Comment by Schwartz10** [comment]
Yeah it happens on a new account. I haven't recently tested on an account that already has a 3box to see if information gets updated (last time it seems like it took some time -- maybe a few hours? -- to sync changes

**Comment by oed** [comment]
Ok, thanks. Will have a closer look at this now. Seems like it could be a major isssue!

**Comment by oed** [comment]
Hm, I'm seeing a different bug when you first set your profile the edit profile page turns black. Will sync with @oznekenzo to see what's up.

**Comment by oznekenzo** [comment]
@oed Thanks for mentioning.  The onboarding modal for new users wasn't properly triggering. That's fixed now

**Comment by oed** [comment]
@Schwartz10 do you get a MM modal like this when you save your profile the first time?

<img width="360" alt="Screenshot 2019-05-27 at 19 34 03" src="https://user-images.githubusercontent.com/3909429/58433251-89741480-80b6-11e9-9e0e-c4400ff8e4bd.png">

**Comment by Schwartz10** [comment]
Hey @oed sorry for the radio silence!

I just tested this again, same thing is happening.

1. I go to 3box.io with a newborn metamask account
2. click to create a profile 
3. sign the consent message (granting 3box.io access to my profile)
4. Enter profile screen, edit some basic data, click save
5. sign the create box message (linking my eth address)
6. profile populates in 3box after refresh
7. https://ipfs.3box.io/profile?address=0xF7395FA6dFB6EF66f77e6705848AF4972F91820a shows:

```js
{
    "status": "error",
    "message": "Address link not found, address does not have a 3Box or is malformed"
}
```
Calling the `getProfile` method in my other application comes back with `{}`

**Comment by oed** [comment]
That's very strange. What's the output of your console on 3box.io? My guess would be that there is some issue in the http request to the address server (that publishes the link) for some reason.

**Comment by oed** [comment]
I assume this is not happening anymore @Schwartz10, closing for now. Please reopen if there are still issues with this.
