### ISSUE TITLE
Rename link functions to "linkAddress"

### ISSUE THREAD

**Issue by oed** [3box/3box-js#464]
Rename:
* `linkAccount` -> `linkAddress`
* `isAccountLinked` -> `isAddressLinked`

We should keep the old functions, but remove their jsdoc and add a `console.warn` that these functions are deprecated in favor of the new ones.

We might also want to move these functions such that they are not part of the core API. Maybe something like `box.utils.linkAddress()` makes more sense?

**Comment by zachferland** [comment]
Are we sure we don't actually want to keep these? @oed you were already passing type through, so they would cover other cases well still, or it is because the api will change for the others, also consume a proof arg or something? 

For address 
linkAccount('ethereum') 
isAccountLinked('ethereum')
