### ISSUE TITLE
Store address link in root-store

### ISSUE THREAD

**Issue by oed** [3box/3box-js#465]
Right now the ethereum_proof is stored as an entry in in the publicStore. Instead we should store this proof as an entry in the rootStore. The proof itself is stored in an ipfs object, then we add an entry to the rootStore that contains the hash of this ipfs object. This gives us the ability to remove the link without having to remove the entire rootStore. Note that this also needs a small change in the pinning-node so that it pins this object when it replicates the rootStore.

The entry in the rootStore will look like this:
```js
{
  type: 'address-link',
  data: <ipfs-cid>
}
```

**Comment by michaelsena** [comment]
Can this be done as an IPLD link?
