### ISSUE TITLE
Failed to open space with dot character

### ISSUE THREAD

**Issue by pedrouid** [3box/3box-js#475]
**Describe the bug**
Tried to open a space with a name that included the dot character (`.`) and 3box failed to open it.

**Example**
Fails with namespace `EXAMPLE_SPACE_V1.0` but it works with `EXAMPLE_SPACE_V1_0`

**Note**
It's not critical but definitely take a look or document it

**Comment by oed** [comment]
Thanks for reporting @pedrouid! We should probably just disallow space names with dots.

**Comment by pedrouid** [comment]
That's I thought as well and then document it on the README

**Comment by oed** [comment]
Or directly in the jsdoc 🙂

**Comment by oed** [comment]
This seems to be resolved already. If the name includes a `. ` the `openSpace` method will throw an error.
