### ISSUE TITLE
Access controller manifest parameters

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-js#481]

**Comment by oed** [comment]
@zachferland Was this fully addressed by my PR or is there something more that's needed?

**Comment by zachferland** [comment]
that and although not necessarily here have small change in js to open entire thread by address

**Comment by oed** [comment]
You should already be able to do that with the current impl!

**Comment by zachferland** [comment]
if address pass it to _load when joinThread, or where you opening another way?

**Comment by oed** [comment]
I meant you can open it like `orbitdb.open(address)`

**Comment by oed** [comment]
But ok I see what you mean :)

**Comment by zachferland** [comment]
oh yeah, definitely

**Comment by zachferland** [comment]
Want to double check all the manifests one more time, should be able to skip publishing mod ac to ipfs. Want make sure i understand exactly how its loading and saving the ACs
