### ISSUE TITLE
Threads Sync/Consistency for following implementation

### ISSUE THREAD

**Issue by zachferland** [3box/3box-js#510]
@oed 

@michaelsena  and @oznekenzo synced on issue later today, and was able to more reliably create it by having multiple tabs open (a flow that sounds a bit more likely with followers maybe). Then can speak to the exact flow better, but created this issue as my quick follow up and to note for you tmrrw.

This may be something orbitdb just doesn't support well, which is not surprising really, due to how indexeddb is shared across  tab instances, I tried it out for a bit to see. Would have expected updates to be shared still, but didn't seem like they were, the head hash could be overwritten back and forth as you switch tabs messing up how it looks to retrieve entries, not sure exactly yet. 

Although not sure this case entirely explains it since this doesn't sound like how you were using  the example to test for it today. But could be once case.

@michaelsena also mentioned getThread not update right away in this case with multiple tabs, so again, would have expected it to update when getting updates from either thread, didn't have a chance to look into this one.

**Comment by oed** [comment]
Ok interesting, thanks @zachferland.

I'll try to recreate the same thing today and think about mitigation strategies. It does make sense that this could be an issue though if orbit is not actively looking for changes to the indexddb.

**Comment by oed** [comment]
@zachferland @oznekenzo this can be closed now right?

**Comment by oznekenzo** [comment]
I think so!! I'll let you do the honors
