### ISSUE TITLE
Can't use 3box-js on Safari

### ISSUE THREAD

**Issue by leonprou** [3box/3box-js#515]
**Describe the bug**
Using Dapps on Safari is hard, we are using `web3-provider-engine` and `ethereum-wallet` to create a provider in the browser. This approach works on Chrome, but fails on Safari.

**To Reproduce**
1. clone my fork of the 3box-js https://github.com/leonprou/3box-js/tree/master
2. run the example app on Safari and Chrome: `npm run example:start`

**Expected behavior**
I should be able to store private and public data, open spaces, these actions not working. But I can open the 3box, and get the private data (I think it's working).

**Actual behaviour**
I see that error on writing to store:
```
Unhandled Promise Rejection: Error: Could not append entry, key "did:3:bafyreidzvky7xkwbna7yjsc6pdlxewpiqcntoujcju7b32ctlhpicmuoe4" is not allowed to write to the log
```

Looking  into it I've found that  `verifyJWT` returns an error: ``Error: Signature invalid for JWT```.. And that happens cause that the elliptic curve is just not correct for some reason.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari, Version 12.1 (14607.1.40.1.4)
 - Version 1.9.1

**Comment by oed** [comment]
Thanks for reporting @leonprou! I've managed to reproduce this locally. Seems like it could be something with how safari handles crypto libraries, but not sure yet.

**Comment by leonprou** [comment]
@oed Yes this looks like so.. Updated the issue with some more info about the error

**Comment by oed** [comment]
Nice @leonprou, we will try to find some time next sprint to have a closer look at this issue! If you discover anything else please let us know in the meantime.

**Comment by leonprou** [comment]
@oed guys any update on this?

**Comment by oed** [comment]
Hey, unfortunately we haven't had a chance to have a closer look at this specifically yet. However, we recently implemented Web3Connect in the 3box.io dapp. And it seems like it's working fine in safari when using portis for example.

**Comment by leonprou** [comment]
@oed Thanks, we tried again and it worked. I think I'll close this.
