### ISSUE TITLE
Make API it's own class that the Box class extends

### ISSUE THREAD

**Issue by oed** [3box/3box-js#521]
Right now the Box class imports the API module that has a bunch of functions and wraps them in static functions on the Box class. Instead of doing this we could let the API module be a class that the Box class can extend. This would remove a lot of clutter from the Box class code.

cc @zachferland Any thoughts on this?

**Comment by zachferland** [comment]
yeah or maybe have it available at box.api to help clear up some confusion with which functions are api calls and which are not, if we want to differentiate much or not
