### ISSUE TITLE
Add api/option for wallets to provide signature 

### ISSUE THREAD

**Issue by danjm** [3box/3box-js#528]
Hi there,

I'm a member of the Metamask team and currently working on integrating 3box to MetaMask. Our initial release of this will just be used to back up a users settings data.

To provide an optimal onboarding experience, we would like to initiate 3box syncing without the user having to confirm a signature request.

This could be possible if 3box allowed for a wallet signed message to be passed as an option to `openBox`. Currently, threebox gets the signature it needs for authentication through a `personal_sign` request in the `openBoxConsent` call made here: https://github.com/3box/3box-js/blob/develop/src/3id/index.js#L184

Naively, it seems that 3box could do something like this:
```
const sig = opts.walletProvidedSignature
        ? opts.walletProvidedSignature
        : await utils.openBoxConsent(normalizedAddress, ethereum)
```
Provided that the `walletProvidedSignature` meets 3boxes specifications.

This would allow metamask and other signers to use 3box internally without our users having to manually confirm a signature request.

If this is doable, I'm happy to help with associated dev work within 3box-js, and happy to discuss more here or via a call

**Comment by oed** [comment]
Hey @danjm this is a great suggestion! We are actually working on exactly this issue right now. We are building an Identity Wallet SDK that allows to pass either and `authSecret` or a `seed`. You can read more about it here: https://github.com/3box/3box/issues/640

In the meantime, is it possible to automatically approve the request if you see that it originates from within MetaMask?

Happy to discuss more and jump on a call :)

**Comment by oed** [comment]
I guess adding an extra option in `openBox` would be quite simple as a quick solution to this particular pain point for now though. Is that something you'd be interested in contributing?

**Comment by danjm** [comment]
> Is that something you'd be interested in contributing?

Yes, I'm happy to contribute that.

**Comment by oed** [comment]
Cool, I'll have a quick look at this tomorrow morning to add a couple of notes for you to start with!

**Comment by oed** [comment]
Ok, three steps to make this happen I believe:

1. Add optional parameter `conentSignature` (in opts object) to `openBox` in `3box.js` file
1. Add optional parameter `conentSignature` (in opts object) to `getIdFromEthAddress` in `3id/index.js` file
1. In the else block in `getIdFromEthAddress` use `conentSignature` for `sig` variable if defined

I think that's it! 
Let me know if anything is unclear :)
