### ISSUE TITLE
Determine if a user has a profile without opening their box

### ISSUE THREAD

**Issue by Schwartz10** [3box/3box-js#536]
**Describe the feature**
This is less of a bug, more of a feature request. But in release `1.10` my app has no way to determine if 3box is going to request a "new profile" signature without opening the user's 3box first. 

**Expected behavior**
I'd love a static method that just tells us if an ethereum address has a 3box profile (or more specifically, if setting information in the user's 3box is going to trigger a create 3box signature request). Something like:

`await Box.hasProfile(ethereumAddress)` would do the trick. Because right now our UI gets out of sync with the 1.10 release, so we can't upgrade.

**Comment by oed** [comment]
It seem like what you are looking for is if the user has a link from their ethereum address to their 3box. You can check this by calling `const config = Box.getConfig(<ethereum-address>)`, and checking if the `config.links` array contains any links. 
I think that should solve your problem!
