### ISSUE TITLE
Threads onUpdate not returning correct value

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#549]
Im having an issue with `thread.onUpdate()`
Ive removed any function to fetch any new posts that have been added to the thread (by clicking "Follow") bc `onUpdate` will do this for me.  
Now, though, when I save a post ('Contact') to the thread (confirmed by the string returned from a successful `thread.post(Contact)`) I see from the logs that `thread.getPosts()` flashes quickly to the correct value (in this case an array of two) only to go back to the previous (now incorrect) value of array of 1 length.  
Reloading the dapp, however, `thread.getPosts()` then shows the correct value of array length 2

**Comment by oznekenzo** [comment]
My mistake, this likely was due to me accidentally calling `thread.onUpdate()` twice through the different login mechanisms.  Seems when I fixed this, the above behavior went away

**Comment by oed** [comment]
Thanks @oznekenzo. Closing this. Please reopen this if the same bug happens again.
