### ISSUE TITLE
`space.joinThread(threadname, opts)` results in error on new accounts

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#550]
Immediately after `space.openSpace(spacename)` (which successfully returns a space), I call `space.joinThread(spacename, opts)` which results in the following error when you're doing this with a new account, or an account with signature states cleared:
('Following' is the spacename provided to openSpace)
```
Error getting thread TypeError: Cannot read property 'Following' of undefined
    at _callee4$ (api.js:203)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:264)
    at Generator.prototype.<computed> [as next] (runtime.js:98)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

in Tokenary with WalletConnect, Im unable to get past this issue.
in Metamask, the above error happens on a fresh account with no entries in the thread.  The second time around, this issue is gone.

I can't tell if this issue is with the 3boxjs or with w3connect, would love some help with this so I can bring it to the attention of the w3c team if necessary

**Comment by oznekenzo** [comment]
@oed @zachferland this is one of the few remaining blockers for Following so would love to get your pass/help on this sometime in the next day or two

**Comment by oed** [comment]
What do you pass as the `opts` object? I assume you pass an ethereum address? Try not passing anything and it should default to the current user.

There is a bug here though. The conditional [here](https://github.com/3box/3box-js/blob/develop/src/api.js#L61) should be:
```js
if (!conf.spaces || !conf.spaces[space] || !conf.spaces[space].DID)
```

**Comment by oznekenzo** [comment]
@oed 
```
    const opts = {
      members: true,
      firstModerator: myAddress,
    };
```

**Comment by oed** [comment]
Yeah, try with just
```js
const opts = {
  members: true
};
```
