### ISSUE TITLE
Example application from 3box docs not working

### ISSUE THREAD

**Issue by tesla809** [3box/3box-js#556]
**Describe the bug**
Example application from 3box docs: https://github.com/3box/3box-js/tree/develop/example
is not working.

This is due to the link routing me to the example folder of the 3box repo.

I thought I could run the app by copying and pasting code into local file. I would have to clone the entire 3box repo and then look within the example folder. It seemed counter intuitive if i just want to play around with the example app.

Perhaps there should be a separate repo with instructions to set up the example. 

**To Reproduce**
1. Go to https://github.com/3box/3box-js/tree/develop/example
2. Copy and add all files to a local folder.
3. Open the file up.

**Expected behavior**
I expected the file to work. 

However, I saw that the file was dependent on express and the path for the main 3box repo.
So I had to yarn install 'express' and replace the 3box script tag to the hosted version.
Then it started to work.

**Desktop (please complete the following information):**
 - OS: MacOS latest
 - Browser: Chrome
 - Version: latest

**Additional context**
The example app should be its own repository and have its own package.json file with its dependancies.

**Comment by oed** [comment]
@tesla809 Did you open the html file directly or execute `$ npm run example:start`? Sorry, maybe it was a bit unclear in the documentation that you need to do that. Check here for reference: https://github.com/3box/3box-js#example

cc @michaelsena

**Comment by dolebas** [comment]
I believe these are the detailed instructions to run the example app?

1. git clone https://github.com/3box/3box-js
2. cd 3box-js
3. npm install
4. npm run example:start

"Open 3box" connects MetaMask properly but nothing happens when I click "Get profile data" or "Query profiles" after sumbitting my eth address which have a profile created via 3box.io

index.js:184 Uncaught TypeError: Cannot read property 'getProfile' of undefined
    at HTMLButtonElement.<anonymous> (index.js:184)

**Comment by oed** [comment]
That seems like a bug @dolebas. Will try to have a look at it soon!

**Comment by oed** [comment]
@dolebas Can you show me the output of your console?

**Comment by dolebas** [comment]
sure! @oed 
![image](https://user-images.githubusercontent.com/27515901/65533776-91c24c00-defe-11e9-9882-722360be8db4.png)

**Comment by oed** [comment]
Hm, seems like it could be some dependency issue.
Can you try running `npm ci` instead of `npm install`?

**Comment by dolebas** [comment]
Yes, it works after running "npm ci"!

**Comment by oed** [comment]
Great, closing this issue :)

**Comment by michaelsena** [comment]
@oed should we update the docs site and the 3box-js readme to include this instruction?

**Comment by oed** [comment]
@michaelsena it's already in the #605 PR ;)
