### ISSUE TITLE
Support ethersjs

### ISSUE THREAD

**Issue by oed** [3box/3box-js#577]
To support the ether.js api with 3box you can use the following code snippet by using the ethers.js wallet interface:

```js
const ethProvider = wallet => {
  return {
    send: (data, callback) => {
      if (data.method === 'personal_sign') {
        wallet.signMessage(data.params[0]).then(result => {
          callback(null, { result })
        })
      } else {
        callback(null, '0x')
      }
    }
  }
}
```

Now you can authenticate a 3box with this wrapper:

```js
const box = await Box.openBox(<ethereum-address>, ethProvider(wallet))

**Comment by ps2-controller** [comment]
At Oed's request, adding a solution for when the private key is generated through EthCrypto and controlled. (Generalizes to any instance when the private key is controlled, so no provider is needed)
pass the following as the second argument in Box.openBox()
```
const ethereum = {
            sendAsync: function (data, callback) {
                let messageHash = EthCrypto.hash.keccak256(data.params[0]);
                let signature = EthCrypto.sign(account.privateKey, messageHash)
                callback(null, {result: signature})
            }
        }
```

**Comment by kenshyx** [comment]
@oed to keep the message human readable(ex in metamask confirmation modal) `data.params[0]` must be an utf8 string, right now it's a hex encoded string.

**Comment by oed** [comment]
@kenshyx I'm pretty sure it has to be hex! It works in MetaMask and all other wallets we've tested with. What wallet are you using?

**Comment by oed** [comment]
I updated the example in the OP to work with some recent changes in 3box-js.

**Comment by kenshyx** [comment]
@oed wallet.signMessage will rehash the message

**Comment by oed** [comment]
> @oed wallet.signMessage will rehash the message

Oh, in Ethers.js? What do you mean by "rehash" exactly? The hex encoding is not a hash.

Do you have any ideas how to solve this? Is there perhaps another signing method that doesn't do this in ethers.js? Thing is if we change it to not be hex encoded it will break for all ethereum-provider wallets.

**Comment by oed** [comment]
@kenshyx I'm not sure I follow. The Wallet interface in ethersjs doesn't seem to show any UX for the user, so I don't understand why you need it encoded as utf-8?

**Comment by kenshyx** [comment]
Yes, you're right I didn't explain the context.
In my tests I've used the [Provider](https://docs.ethers.io/ethers.js/html/api-providers.html) from ethers.js to connect to Metamask(Web3Provider).
After this you can get the current account by calling `provider.getSigner()`. I've used this instance in your example for the `wallet` value, so when a send/sendAsync call occurs it will trigger  the Metamask confirmation modal.

**Comment by oed** [comment]
@kenshyx If you have access to MetaMask, why don't you just use `window.ethereum` for 3box?

**Comment by oed** [comment]
We have released a library called IdentityWallet. From now on it's recommended to use that instead. See the documentation here: https://docs.3box.io/build/wallets
