### ISSUE TITLE
Create basic architecture diagram for Ghost Threads

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-js#625]

**Comment by oed** [comment]
This is a bit too abstract I think. Can you add a few sentences of what this needs to show @michaelsena ?

**Comment by michaelsena** [comment]
Maybe online peers (storage), signaling server (bootstrap/peer discovery), pubsub room (networking), etc, etc. Basically how messages are sent and stored, and how nodes come online. Just to give people a visual to supplement the words we have. @oed
