### ISSUE TITLE
When saving data seeing MetaMask - RPC Error: "message" must be a nonempty string. 

### ISSUE THREAD

**Issue by tibetsprague** [3box/3box-js#647]
**Describe the bug**
Whenever I call `Box.openBox` I see the following error in the console

`MetaMask - RPC Error: "message" must be a nonempty string. 
{code: -32603, message: ""message" must be a nonempty string.", data: {…}, stack: "Error: "message" must be a nonempty string.↵    at…eogaeaoehlefnkodbefgpgknn/background.js:1:1195294"}
code: -32603
data: {originalError: {…}}
message: ""message" must be a nonempty string."
stack: "Error: "message" must be a nonempty string.↵
`

**To Reproduce**
Working on setting up a staging server for you to see the behavior but running into weird build issues. I will add here when it's up. 

**Expected behavior**
Data is saved to 3box with no errors. Right now it does eventually save to 3box (after 10+ seconds usually). 

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 78.0.3904.70

**Additional context**
It was recently working fine without error and then the errors started happening.

**Comment by oed** [comment]
Thanks for reporting. Any chance you could provide the whole stack trace?
Is this blocking `Box.openBox` from opening, or are things still working?

> It was recently working fine without error and then the errors started happening.

I wonder if something was maybe changed in metamask? 🤔

**Comment by tibetsprague** [comment]
Things are still working. I doubt the stack is very useful:

`"Error: "message" must be a nonempty string.
    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1147873)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1149623)
    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1149909)
    at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1196046)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1195294"`

**Comment by oed** [comment]
Thanks. Hopefully this isn't causing any other issues. Let us know if anything changes with this!

**Comment by tibetsprague** [comment]
Well the other thing we are seeing which started around the same time as this, but may be unrelated, is that saving any data to a profile or space now takes 10+ seconds every time. It used to be much faster. Is this known @oed ?

**Comment by oed** [comment]
@tibetsprague is every `space.public.set` call takiing 10+ seconds? If so that should definitely not be the case!

**Comment by tibetsprague** [comment]
box.public.setMultiple is taking around 10 seconds every time, space.public.set is also taking around that though i have seen it take up to 30 seconds

**Comment by oed** [comment]
I'll have to investigate this. It shouldn't take more than a few ms. Is this happening for all accounts or just a few specific ones?

**Comment by tibetsprague** [comment]
yes, every account ive tried

**Comment by oed** [comment]
I'm not able to recreate this. What version of 3box-js are you using? 
How are you measuring the time it takes? Can you try this?
```js
console.time('set space')
space.public.set('aa', 'bb').then(() => {
  console.timeEnd('set space')
})
```

Is [this your code](https://github.com/daostack/alchemy/pull/1198/files#diff-c6e6d86de81efe35087f5b368cb5225cR75-R87)? 
If so it looks like the problem is that you call `Box.openBox` every time you want to set data. This function should only be called once to create an instance of 3box that is used every time you want to update data.

**Comment by tibetsprague** [comment]
Yes that is the code. 3box v1.13.1. And you're right, its the openBox that is taking so long (right now im seeing around 21 seconds every time) though the box.public.setMultiple is still taking taking 7-10 seconds itself. So your suggestion is that we store the box object in Redux, or localStorage or something? That seems odd to me. It would be nice if openBox handled this kind of caching on its own. Otherwise we have to either serialize the object and unserialize when we want to use, or find some way to pass the box object around our app. Also this code used to be much speedier up until a couple weeks ago.

**Comment by oed** [comment]
Yeah, I would recommend using redux to store the box object. The reason for this is that it needs to have an instance of ipfs and orbitdb internally. I definitely agree that it would be nice if 3box did this on it's own. We've been hesitant to do it since it would basically mean adding ipfs and orbitdb to the global scope. 
If you have other ideas we would be more than happy to consider them :)

**Comment by oed** [comment]
@tibetsprague Hey, are you still experiencing the first error you reported?

**Comment by tibetsprague** [comment]
the original error message seems to have gone away!
