### ISSUE TITLE
Type error in 3ID when using Authereum

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#648]
Am getting the error `Cannot read property 'toLowerCase' of undefined` when trying to login using Authereum at line 1003 in index.js of 3id - can't tell if this is still an issue with Authereum (they should always pass an address) - or a small check in the lib - lmk

the snippet failing in 3id:
```
              case 8:
                normalizedAddress = address.toLowerCase();
                serialized3id = localstorage.get(STORAGE_KEY + normalizedAddress);

                if (!serialized3id) {
                  _context16.next = 14;
                  break;
                }

                if (opts.consentCallback) opts.consentCallback(false);
                _context16.next = 26;
                break;
```

**Comment by oed** [comment]
Moved this issue to 3box-js since this is where the error seems to be happening.
Are you sure you actually get the ethereum address from authereum? Looks like it's undefined.

**Comment by oed** [comment]
Is this still an issue @oznekenzo?

**Comment by oznekenzo** [comment]
Nope - closing
