### ISSUE TITLE
Can not verify signed Claims from 3ID

### ISSUE THREAD

**Issue by froid1911** [3box/3box-js#651]
**Describe the bug**
When I open a space, a new 3ID is generated. If I sign with the appropriate private key of the 3ID a claim, then I expect that the signed claim could be verified through the idUtils, but its not.

**To Reproduce**
1. Open a Box ```const box = await Box.openBox(address, provider)```
2. Open a Space ```const space = await box.openSpace(spacename)```
3. Sign a payload with ```const userClaim = await box._3id.signJWT(
      payload,
      { space: space._name }
    );```
4. Verify JWT with ```const result = await Box.idUtils.verifyClaim(userClaim);```
5. Throws error:
```
Uncaught (in promise) TypeError: Cannot read property '-1' of null
    at BN.bitLength (bn.js:598)
    at Point._hasDoubles (base.js:303)
    at Point.mul (short.js:403)
    at KeyPair.getPublic (key.js:63)
    at EC.verify (index.js:158)
    at KeyPair.verify (key.js:108)
    at index.js:51
    at Array.find (<anonymous>)
    at ES256K (index.js:50)
    at index.js:238
    at async Home.sendVerificationRequest (Home.js:56)
```

**Expected behavior**
Expected an Object with DID Document and Verified decoded claim.

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser Chrome

**Comment by oed** [comment]
This is a quirk with space 3IDs. They way you can verify the claims is to call:
```js
const result = await Box.idUtils.verifyClaim(userClaim, { auth: true });
```
