### ISSUE TITLE
Ghost thread getPosts returning posts without postId

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#668]
The ghost threads api end point is not returning postIds with each post.

**Comment by oed** [comment]
Currently `postId` is not supported by ghost threads. We might want to add them in the future though. Do you need this for a particular reason?

**Comment by oznekenzo** [comment]
One of our users wants to hack on the chatbox component for the gitcoin issues - it's likely we need it for https://github.com/3box/3box-chatbox-react/issues/22 or the solutions might get pretty hacky 😬 no?

**Comment by oed** [comment]
I'm not sure :) Why is `postId` needed for this hack?

**Comment by oznekenzo** [comment]
The gitcoin bounty calls for attributing likes to messages

**Comment by michaelsena** [comment]
Already fixed this. Closing the issue.
