### ISSUE TITLE
`linkAddress` functionality no longer working in v1.14.0

### ISSUE THREAD

**Issue by adamsoffer** [3box/3box-js#675]
**Describe the bug**
Calling `linkAddress` no longers links an external address after updating from v1.13.2 to v1.14.0

**To Reproduce**
1. Install v1.13.2 and call `linkAddress` on an external accout you'd like to link. Notice it works.
2. Install v1.14.0 and repeat step 1. There's no error, but the external account doesn't in fact get linked.

**Expected behavior**
Calling `linkAddress` should link an external account

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser Brave
 - Version v1.14.0

**Comment by oed** [comment]
Hey @adamsoffer thanks reporting! Can you provide an example of how you are calling `linkAddress`?

**Comment by adamsoffer** [comment]
Sure! Looks something like this...

```js
const message = `Create a new 3Box profile<br /><br />-<br />Your unique profile ID is ${threeBoxSpace.did}<br />Timestamp: ${timestamp}`

const proof = {
  version: 1,
  type: 'ethereum-eoa',
  message: message.replace(/<br ?\/?>/g, '\n'),
  timestamp,
  signature,
}
await box.linkAddress({
  type: 'ethereum-eoa',
  proof: _args.proof,
})
```

**Comment by oed** [comment]
I see that you call `replace` on the `message` @adamsoffer. Which of the two versions are you signing? You have to provide a signature over the one that is included in the proof!

**Comment by adamsoffer** [comment]
Ah yeah that's just so I can render the message in HTML. I am indeed signing the message with `\n`. Works in `1.13.2`.

**Comment by oed** [comment]
Ok good. Can you try running this and see if it throws any errors?
```js
const { validateLink } = require('3id-blockchain-utils')
const validated = await validateLink(proof)
console.log(validated)
```
I'm wondering if anything broke when we updated to use this library.

**Comment by adamsoffer** [comment]
@oed No errors. Returns the added proof.
```
{
  version: 1
  type: "ethereum-eoa"
message: "Create a new 3Box profile↵↵-↵Your unique profile ID is 
  did:muport:QmenZPWdYkzwrTrNTcKLfbzNH4scE4pGpWvmxHhvYg22Go↵Timestamp: 1576515319"
  timestamp: 1576515319
  signature: "0x5ec00c3d6c75cbbe19fe5a62ee4c191e369a03a615c658e2b97a8ef8802940873e073667c5619c48e482f0d603eb812275c7aa55242479f6e6314bd89803542a1b" 
  address: "0x0fd4f4bca7bed48681dbbaedd94fe39f474090ed"
  did: "did:muport:QmenZPWdYkzwrTrNTcKLfbzNH4scE4pGpWvmxHhvYg22Go"
}
```
