### ISSUE TITLE
Version 1.16 doesn't load twitter verifications on all accounts (that work with  <= v1.15)

### ISSUE THREAD

**Issue by JasoonS** [3box/3box-js#716]
**Describe the bug**
For Some ethereum addresses, v1.16 doesn't load the twitter verification correctly.

**To Reproduce**
Run this code with a prior version of 3box installed:
```

const { getProfile, getVerifiedAccounts } = require("3box/lib/api");
let user1 = "0x9AF481276b075e036BC23E887a8Bd275e69Ef74C";
let user2 = "0x373d8388C1Ab8F88B7B9C4EAc8C1531D683D9deE";
getProfile(user1).then(profile => {
  console.log({ profile });
  getVerifiedAccounts(profile).then(verifiedAccounts => {
    console.log({ verifiedAccounts });
  });
});
getProfile(user2).then(profile => {
  console.log({ profile });
  getVerifiedAccounts(profile).then(verifiedAccounts => {
    console.log({ verifiedAccounts });
  });
});
```

Note the output particularly of the `{ verifiedAccounts }`. Then switch to the latest version of 3box v1.16.1

And you will notice that there is no twitter verification.

**Expected behavior**
v1.16.1 should also load twitter verifications.

**Screenshots**
To see it I'll share two different wildcards (and their users):
https://ui-git-faultytwitterverifications.jasoons.now.sh/#explorer/details/Aruma 
In this link the first profile-hover uses v1.3.0 and the second one is upgraded to v1.16.0

and https://ui-git-faultytwitterverifications.jasoons.now.sh/#explorer/details/Llajuita
In this second link both v1.3.0 and v1.16.0 work perfectly.

**Desktop (please complete the following information):**
 - OS: ubuntu19.04
 - Browser: firefox+chrome

**Comment by JasoonS** [comment]
Actually this issue really confuses me. It isn't working on V1.15 or lower anymore.

All I know is that the "0x9AF481276b075e036BC23E887a8Bd275e69Ef74C" and "0x373d8388C1Ab8F88B7B9C4EAc8C1531D683D9deE" are twitter verified. But the `getVerifiedAccounts` function doesn't show it. On the `hover-profiles` both of these accounts twitter verifications show.

**Comment by oed** [comment]
Not totally sure why, but it seems like this is working on latest develop. Can you test this with `3box@1.16.2-beta.1` and see if it works? I'll make sure to let you know when the new version is released!

**Comment by JasoonS** [comment]
@oed This is working on `3box@1.16.2-beta.1` :tada: Thanks for the help!

It didn't work initially when I tried `3box@1.16.2-beta.3`; but maybe that was a npm caching issue or something weird.

**Comment by oed** [comment]
@JasoonS yeah, sorry i've been testing some other stuff with the later beta releases keep using beta.1 for now until we release the next version 👍

**Comment by JasoonS** [comment]
Perfect. Once again, I really appreciate it!

**Comment by oed** [comment]
@JasoonS new 3box version that fixes this has been released!
