### ISSUE TITLE
Cannot add 3box with yarn

### ISSUE THREAD

**Issue by j-mars** [3box/3box-js#723]
**Describe the bug**
Trying to install the package with yarn gives the following error:

yarn
yarn install v1.22.0
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/3box: Not found".

**To Reproduce**
in a project do yarn add 3box or yarn if you have it in your package.json

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45543880/74333787-87f79300-4d90-11ea-8e15-6f813cd9cbdf.png)

**Desktop (please complete the following information):**
- Ubuntu 18.04.4 LTS on WSL

**Comment by oed** [comment]
This is a bug in yarn. You can find a workaround here: https://github.com/yarnpkg/yarn/issues/7902

It also looks like they just released a fix for it.
