### ISSUE TITLE
Link consent error on new accounts

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#737]
Several reports of the error `Uncaught (in promise) Error: Link consent message must be signed before adding data, to link address to store`

I haven't noticed as I was using a preexisting account.
Then created a new Portis account and saw the error myself on `openBox` and on `set`s

I set up and recreated the issue on the `test/linkConsentError` for you to try

**Comment by zachferland** [comment]
thanks, only new portis accounts? or new metamask accounts as well?

**Comment by oznekenzo** [comment]
Haven’t tried with MetaMask, but my guess is yes, as other people have seen
it using other wallets

**Comment by oed** [comment]
seems related to https://github.com/3box/3box-js/issues/700

**Comment by oznekenzo** [comment]
definitely @oed

**Comment by zachferland** [comment]
Resolved by https://github.com/3box/js-3id-blockchain-utils/pull/7
