### ISSUE TITLE
Quick/naive look at improving DX for 3box-js

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-js#738]

**Comment by oed** [comment]
Can you please clarify / provide more context?

**Comment by oznekenzo** [comment]
Yeah, we spoke a sprint or two ago about how we might be able to make
easier to use or to understand the different functionalities of the library
and that it might be worth the time to put some thinking into this.  If you
think it’s not necessary as it might not even be feasible to implement or
bc of all the other work going on, we can close it or move it to the
backlog.

“Naive” in that this exercise would be somewhat ignorant of the complexity
under the hood and focus mainly on ease of use/understandability.

**Comment by oznekenzo** [comment]
Quick write-up here, two suggestions to fix low-hanging problems, nothing major:
https://www.notion.so/threebox/DX-Write-Up-07a09e2ba8a5492dacfd79754cd9d6c8
@oed @michaelsena
