### ISSUE TITLE
Error during "npm i 3box" on v1.17.1

### ISSUE THREAD

**Issue by guillempuche** [3box/3box-js#743]
**The problem**
I can't install the 3Box package.

The error is in one of the 3Box dependencies.

**To Reproduce**
```
npm create-react-app cites-web
cd cites-web
npm i 3box
```
**Expected behavior**
Install 3Box package locally.

**Screenshots**
![3box](https://user-images.githubusercontent.com/3519924/77105011-3be9df00-6a1d-11ea-9782-68722e8ef3b4.png)

**Versions**
- OS: Ubuntu 18.04
- Node: 10.19.0
- npm: 6.13.4
- create-react-app: 3.4.0
- 3box: 1.17.1

**Comment by oed** [comment]
Thanks for reporting. Seems like it's related to one of the ipfs subdependencies. Is it possible to install a different version of `multicodec`?

**Comment by guillempuche** [comment]
I didn't have git installed.

Now I have. But it doesn't install, I have a different error:
![screenshots-merged](https://user-images.githubusercontent.com/3519924/77110095-4d36e980-6a25-11ea-97ab-25df5855bb12.png)

**Comment by oed** [comment]
@guillempuche It's really hard to read your image, would be more helpful if you could use pastebin in the future. 
My guess is that you have something that is missconfigured on your system however.

**Comment by guillempuche** [comment]
@oed, the image has great quality. If you download it, you will read fantastically.

I developing on Linux since 1 monthys. I didn't have any problem installing npm packages, but 3box.

**Comment by guillempuche** [comment]
**PROBLEM**
I have some [underconfiguration on my Linux](https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached)

**SOLUTION**
["System limit for number of file watchers reached"](https://stackoverflow.com/a/55763478/9192954)
