### ISSUE TITLE
Deploying to gcloud a ssr app blows up build when adding 3box npm 1.17.1

### ISSUE THREAD

**Issue by nategeier** [3box/3box-js#746]
**Describe the bug**
Works perfectly locally, but when deploying my next.js servers-side react app to Google App Engine the deploy fails. By simply commenting out any imports to 3box and removing the package in package.json the deploy works perfectly.

**To Reproduce**
This might be a long one, but create a `next.js` react app https://nextjs.org/
and try deploying that to gcloud, then add 3box and see if you get the issue too.

**Expected behavior**
Deploys to gcloud 📈

**Desktop (please complete the following information):**
 - OS: mac 10.15.2

**Additional context**
The most useful output from the below seems to be `"canonicalCode":"INVALID_ARGUMENT"`,
which seems to point to point to removing my `package-lock.json` (did every time), after trying it all, popping it in `.cloudeignore`  removing node_modules, re-installing packages over and over I'm looking to see if your team has run into this yet.

Sums up my issue, but removing the lock serval time did not solve it. https://stackoverflow.com/questions/54130113/error-canonicalcode-invalid-argument-google-cloud

When deploying here is the output:

Updating service [default]...failed.
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build 6901133c-aa4e-4490-9cbd-0b4edacc680a status: FAILURE.
Build error details: {"error":{"errorType":"BuildError","canonicalCode":"INVALID_ARGUMENT","errorId":"8320646F","errorMessage":"INFO     FTL version node-v0.17.0\nINFO     Beginning FTL build for node\nINFO     FTL arg passed: exposed_ports None\nINFO     FTL arg passed: cache_repository us.gcr.io/thing-1d2be/app-engine-tmp/build-cache/ttl-7d\nINFO     FTL arg passed: tar_base_image_path None\nINFO     FTL arg passed: export_cache_stats False\nINFO     FTL arg passed: builder_output_path \"\"\nINFO     FTL arg passed: name us.gcr.io/thing-1d2be/app-engine-tmp/app/ttl-2h:9a84ac21-289a-431d-ae21-1d7fa336a7cf\nINFO     FTL arg passed: ttl 168\nINFO     FTL arg passed: global_cache False\nINFO     FTL arg passed: cache True\nINFO     FTL arg passed: upload True\nINFO     FTL arg passed: sh_c_prefix False\nINFO     FTL arg passed: fail_on_error True\nINFO     FTL arg passed: base us.gcr.io/gae-runtimes/nodejs10:nodejs10_202010_19_0_RC00\nINFO     FTL arg passed: output_path None\nINFO     FTL arg passed: cache_key_version v0.17.0\nINFO     FTL arg passed: cache_salt \nINFO     FTL arg passed: directory /workspace\nINFO     FTL arg passed: entrypoint None\nINFO     FTL arg passed: additional_directory /.gaeconfig\nINFO     FTL arg passed: destination_path /srv\nINFO     FTL arg passed: verbosity NOTSET\nINFO     starting: full build\nINFO     starting: builder initialization\nINFO     Loading Docker credentials for repository 'us.gcr.io/gae-runtimes/nodejs10:nodejs10_20200f0_19_0_RC00'\nINFO     Loading Docker credentials for repository 'us.gcr.io/thing-1d2be/app-engine-tmp/app/ttl-2h:9a84ac21-289a-431d-ae21-1d7fa336a7cf'\nINFO     builder initialization took 0 seconds\nINFO     starting: build process for FTL image\nINFO     starting: rm_node_modules\nINFO     rm_node_modules rm -rf /workspace/node_modules\nINFO     `rm_node_modules` stdout:\n\nINFO     rm_node_modules took 0 seconds\nINFO     using descriptor:package-lock.json\nINFO     using descriptor:package.json\nINFO     starting: checking_cached_packages_json_layer\nDEBUG    Checking cache for cache_key\nINFO     No cached base image found for entry: us.gcr.io/thing-1d2be/app-engine-tmp/build-cache/ttl-7d/node-   No cached dependency layer for\nINFO     [CACHE][MISS] v0.17.0:NODE-\\nINFO     checking_cached_packages_json_layer took 0 seconds\nINFO     starting: building_packages_json_layer\nINFO     starting: npm_install\nINFO     npm_install npm install --production\nINFO     `npm_install` stdout:\n\n\u003e git-validate@2.2.4 install /workspace/node_modules/ipfs/node_modules/git-validate\n\u003e node bin/install\n\n\n\u003e gc-stats@1.4.0 install /workspace/node_modules/ipfs/node_modules/gc-stats\n\u003e node-pre-gyp install --fallback-to-build\n\n[gc-stats] Success: \"/workspace/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-linux-x64/gcstats.node\" is installed via remote\n\n\u003e ursa-optional@0.9.10 install /workspace/node_modules/ipfs/node_modules/libp2p-websocket-star-rendezvous/node_modules/ursa-optional\n\u003e node rebuild.js\n\n\n\u003e keccak@2.1.0 install /workspace/node_modules/ipfs/node_modules/ethereumjs-block/node_modules/keccak\n\u003e npm run rebuild || echo \"Keccak bindings compilation fail. Pure JS implementation will be used.\"\n\n\n\u003e keccak@2.1.0 rebuild /workspace/node_modules/ipfs/node_modules/ethereumjs-block/node_modules/keccak\n\u003e node-gyp rebuild\n\nmake: Entering directory '/workspace/node_modules/ipfs/node_modules/ethereumjs-block/node_modules/keccak/build'\n  CXX(target) Release/obj.target/keccak/src/addon.o\n  CC(target) Release/obj.target/keccak/src/libkeccak-64/Ke.

### Notice the 3box in last part^^^
`npm_install` stdout:\n\n\u003e git-validate@2.2.4 install /workspace/node_modules/3box/node_modules/ipfs/node_modules/git-validate\n\u003e node bin/install\n\n\n\u003e gc-stats@1.4.0 install /workspace/node_modules/3box/node_modules/ipfs/node_modules/gc-stats\n\u003e node-pre-gyp install --fallback-to-build\n\n[gc-stats] Success: \"/workspace/node_modules/3box/node_modules/ipfs/node_modules/gc-stats/build/gcstats/v1.4.0/Release/node-v64-linux-x64/gcstats.node\" is installed via remote\n\n\u003e ursa-optional@0.9.10 install /workspace/node_modules/3box/node_modules/ipfs/node_modules/libp2p-websocket-star-rendezvous/node_modules/ursa-optional\n\u003e node rebuild.js\n\n\n\u003e keccak@2.1.0 install /workspace/node_modules/3box/node_modules/ipfs/node_modules/ethereumjs-block/node_modules/keccak\n\u003e npm run rebuild || echo \"Keccak bindings compilation fail

### Build log only error is:
```
ERROR: build step 1 "gcr.io/gae-runtimes/nodejs10_app_builder:nodejs10_20200223_10_19_0_RC00" failed: step exited with non-zero status: 1
```

**Comment by dkent600** [comment]
Related?  https://github.com/ipfs/js-ipfs/issues/2986

**Comment by orenyodfat** [comment]
similar issue on our end ...it increase  dramatically our Heroku build slug size ...

**Comment by oed** [comment]
@nategeier would you mind trying this again. The new 3box version `1.20.0` build should be almost 1 MB smaller.

**Comment by dkent600** [comment]
Confirmed fixed, thanks!

**Comment by nategeier** [comment]
> @nategeier would you mind trying this again. The new 3box version `1.20.0` build should be almost 1 MB smaller.

Trying to test but looks like my 3box wall account dropped/lost my info again. Trying to save my account `0x66268791b55e1f5fa585d990326519f101407257` but getting a forever 
![Screen Shot 2020-06-19 at 12 53 54 PM](https://user-images.githubusercontent.com/838839/85125445-f0b5b700-b22b-11ea-8239-0ed32f7dbc33.png)

**Comment by oed** [comment]
@nategeier How loading your account on 3box.io is related to the issue described above?

**Comment by nategeier** [comment]
> @nategeier How loading your account on 3box.io is related to the issue described above?

Mainly venting frustration just trying to this this account to work after a year. The good news is, the new package deployed, so closing this issue now. Page load speed test is now 50% better :)

**Comment by oed** [comment]
Thanks @nategeier, replied to your question about the account in the discord :)
