### ISSUE TITLE
Spec agnostic auth provider

### ISSUE THREAD

**Issue by oed** [3box/3box-js#748]
Is this handled by web3modal?
Do we just show a list of all providers?
Do users need to pick their network, then pick their provider?
Etc.
Possibly coordinate with Pedro.

**Comment by zachferland** [comment]
Most details here - https://github.com/3box/3id-connect/pull/17/commits/4d68780c99f0fe1fe7e916e9e6d1f7bdff1b3ec0 

In readme and in src/authProviders/abstractAuthProvider.js

Likely some details will be added in 3id-blockchain-utils as well and referenced in 3id-connect. May be some minor changes until finalized and based on feedback.

**Comment by zachferland** [comment]
@oed ^ authProvider

**Comment by oed** [comment]
Thanks @zachferland! Looks good from a fast glance :)
