### ISSUE TITLE
Recommended content security policy rules

### ISSUE THREAD

**Issue by miguelmota** [3box/3box-js#753]
Hey guys, is there a list of all domains 3boxjs connects to? I'm tightening down frontend content security policy rules and not sure what are all the hosts that should be whitelisted for the connect-src policy

**Comment by oed** [comment]
Good question. I think all domains should be configured in [`config.js`](https://github.com/3box/3box-js/blob/develop/src/config.js). 
Iirc the infura domain is not being used anymore cc @zachferland

**Comment by oed** [comment]
Closing this @miguelmota. Please let us know if you have any further questions about this.

**Comment by miguelmota** [comment]
Thanks @oed allowing the domains listed in the config file worked
