### ISSUE TITLE
3box within Workers

### ISSUE THREAD

**Issue by wagner-daniel** [3box/3box-js#754]
At the moment I am migrating Totem to WebWorkers for better performance. 3box works fine, but it needs a small adjustment.

In the dependency ipfs-mini is on call to the window object, which is not available in workers.

I opened a issue (https://github.com/SilentCicero/ipfs-mini/issues/14) there and submitted a working pull request (https://github.com/SilentCicero/ipfs-mini/pull/15).

All you need to do is upgrading the dependency, when the request gets merged.

If someone has the same problem a not ideal but functioning workaround is to edit the line I changed in the pull request in your node_modules/ipfs-mini directory, it works, but it breaks again when you reinstall dependencies, so do not use in production.

**Comment by oed** [comment]
Hey, thanks for bringing this up! 'ipfs-mini' is not actually used in 3box anymore and should be removed! 
It's imported here but never used: 
https://github.com/3box/3box-js/blob/5ad3989a51e67791716ef4c091a7507e174edb10/src/3id/index.js#L5

We will remove it eventually, but if you want you can make a PR!

**Comment by oed** [comment]
Solved by #755 
This will be part of the next 3box release
