### ISSUE TITLE
Accounts won't link to addresses under certain conditions

### ISSUE THREAD

**Issue by msterle** [3box/3box-js#757]
Accounts can get into a state where they cannot create a link between an address and a did on the address server. 3box-js won't try to post the link if they have a local proof in their rootstore, even if the address server doesn't have a record of the link. This can happen if the original request failed or was aborted after the proof was written to ipfs and stored in the rootstore,

The `isAddressLinked` function should be updated to check both local and remote state.

https://github.com/3box/3box-js/blob/9069d90e8d390aa44a4b0adc8dc95b03144c30e3/src/3box.js#L349

---

reports:
- nategeier through DM
- https://discordapp.com/channels/484729862368526356/681962660874682573/696532469717008504

**Comment by oed** [comment]
This should be solved by #798
