### ISSUE TITLE
box.openThread fail with "Could not find appropriate DID for address" for Persistent Thread in a New Space

### ISSUE THREAD

**Issue by think-in-universe** [3box/3box-js#761]
### Describe the bug

**Background**: I'm working on 3Box integration with Kickback: https://github.com/wearekickback/app/pull/335, and to meet the needs of a chat per each event, I have extended the ChatBox by @oznekenzo to support Persistent Thread: https://github.com/open-tribe/3box-chatbox-react/tree/smart-chat

When testing the integration with Kickback, we found that the `openThread` failed with a Persistent Thread at this line: https://github.com/open-tribe/3box-chatbox-react/blob/7e5172d3d616a8ed1031e74bd3ad3eb0c7f26ab2/src/ChatBox.jsx#L108, with error `Could not find appropriate DID for address 0xf43......`, and you cannot post because the thread is not fetched. 

**PLEASE NOTE:** this error only happens when (1) the thread is a Persistent Thread; (2) the space doesn't exist. If either the thread is a Ghost Thread, or if the space already exists (e.g. MyFollowings), the error will not appear. 

The forked chatbox changed the logic of initialization of a thread as below:

```js
    const options = !!this.props.persistent ? {
        firstModerator: this.props.firstModerator || ethereum.selectedAddress,
        members: !this.props.open
      } : {
        ghost: true
      };

    const box = await Box.create(ethereum);
    const thread = await box.openThread(spaceName, threadName, options);
    const dialogue = await thread.getPosts();
```

source code: https://github.com/open-tribe/3box-chatbox-react/blob/7e5172d3d616a8ed1031e74bd3ad3eb0c7f26ab2/src/ChatBox.jsx#L97

### To Reproduce
1. Clone the repository https://github.com/open-tribe/3box-chatbox-react, and switch to `smart-chat` branch
2. Run `npm install`
3. Please make sure in `./examples/Example.js`, the `spaceName` (line 56) is set to `Kickback`, and `persistent` (line 75) is enabled. 
4. Run `npm run start`
5. See error in console
6. You cannot post message because the thread is not fetched. 

### Expected behavior

The example project in https://github.com/open-tribe/3box-chatbox-react/tree/smart-chat, can fetch thread, and then post message successfully. 

### Screenshots

**Error**

- console

![image](https://user-images.githubusercontent.com/46699230/79491964-dc014b00-8051-11ea-8945-643076e78d6e.png)

**Debug**

- throw error:

![image](https://user-images.githubusercontent.com/46699230/79491830-99d80980-8051-11ea-8bd5-c8eacc5f5c9d.png)

- conf.spaces doesn't contain `Kickback`:

![image](https://user-images.githubusercontent.com/46699230/79491857-a6f4f880-8051-11ea-9e64-fd4651020196.png)

### Desktop (please complete the following information):
 - OS: MacOS 10.13.1
 - Browser: Chrome, Version 80.0.3987.163 (Official Build) (64-bit)

### Additional context

The issue doesn't happen to Ghost Thread, or when use an existing space.

**Comment by think-in-universe** [comment]
@oed @zachferland could you please help take a look? 

might be related to https://github.com/3box/3box-js/issues/752

**Comment by oed** [comment]
I believe this is because the user you are using for the `firstModerator` has never opened the given space. Currently it's required that the first moderator has opened the space in which the thread is in in order to become a moderator or member of a thread within that space.

If you change you're code example above to something like this I think it should work:
```js
const box = await Box.create(ethereum);
await box.auth([spaceName], { address: ethereumAddress });
const thread = await box.openThread(spaceName, threadName, options);
const dialogue = await thread.getPosts();
```

**Comment by think-in-universe** [comment]
@oed thanks for the kind help!

thanks for the suggestion. I have tried that yesterday after you suggested. but the error is exactly the same. should be `ethereumAddress` be the address for the first moderator or the address of the current user? I tried both, but neither works. 

I pushed this change to https://github.com/open-tribe/3box-chatbox-react/commit/e293092f2e676ae02d9fadf454c5438e998bc6b7#diff-be21e387b427f879fa0465bf0e3e6ce0R110 and https://github.com/open-tribe/3box-chatbox-react/commit/4a2a8c867f050c5126d5ef758d39259ff5e1c1d0. 

If you want, you can have a try following the reproduce steps.

**Comment by oed** [comment]
I think this is basically the same issue as described in #761
