### ISSUE TITLE
Bundle & heroku slug size massively increased in 1.17.1

### ISSUE THREAD

**Issue by tibetsprague** [3box/3box-js#762]
After updating to 1.17.1 our deploys to Heroku started failing because the slug size went way up. It seems like the main culprit is ipfs 0.40.0 which adds a ton to both the bundle and slug size. Feel free to close this issue since it's probably just an ipfs issue but I thought you should at least be aware.

**Comment by oed** [comment]
Thanks for highlighting @tibetsprague! Yes this is an ipfs issue and I believe it can be solved by updating ipfs to the latest version. We are currently blocked by OrbitDB which need to add support for the latest version. 
https://github.com/orbitdb/orbit-db/pull/767

**Comment by tibetsprague** [comment]
thanks @oed !

**Comment by dkent600** [comment]
@oed Looks like orbitdb has a [new release that should fix this problem](https://github.com/orbitdb/orbit-db/releases/tag/0.24.1).    Any ETA on pulling this into 3Box?

**Comment by oed** [comment]
Hey @dkent600 we are currently working on updating to the latest ipfs and orbitdb versions. Expect an update within the next few weeks :) 
(Currently debugging some incompatibilities with the new ipfs version)

**Comment by zachferland** [comment]
IPFS version in updated in  3boxjs v1.20.0 release, decreased build/bundle size by almost 1mb. We have some further changes over coming weeks that may decrease a bit more and ipfs is continuing to work on this. Closing issue for now.
