### ISSUE TITLE
Cannot open 3box with independent implementation of web3modal

### ISSUE THREAD

**Issue by j-mars** [3box/3box-js#771]
**Describe the bug**
If I implement web3modal independently I cannot open 3box with 'Box.openBox' giving the following error: 

"Error: Provider returned signature from different account than requested"

**To Reproduce**
`
Initiate web3modal separately (e.g. with Torus):

      const web3Modal = new Web3Modal({
        providerOptions: {
          torus: {
            package: Torus, // required
            options: {
              network: "https://localhost:8545"
             }
          }
        }
      });

      const provider = await web3Modal.connect();
      
      const web3instance = new Web3(provider);

     await Box.openBox(web3instance.currentProvider.selectedAddress, web3instance.currentProvider)
`
____

if I try this instead:

`
const box = await Box.create(web3instance.currentProvider)
await box.auth("MyFollowing", {address: web3instance.currentProvider.selectedAddress})
`
it gives the following error: 

"TypeError: Cannot read property 'is3idProvider' of undefined"

**Expected behavior**
Authentication on 3box to happen normally without using 3IdProvider (custom implementation of web3Modal)

**Desktop (please complete the following information):**
 - W10 WSL

**Smartphone (please complete the following information):** - Brave Browser, latest version

**Comment by oed** [comment]
@j-mars What version of 3box-js are you on?
cc @zachferland

**Comment by j-mars** [comment]
1.18.0

Guess you had an update which slipped by me, will try again.

**Comment by j-mars** [comment]
Updated to 1.18.1

Getting this error now (very inconclusive) at the same point, this time before prompting me the signature:

"Error: invalid block
    at Object.put (http://localhost:3000/static/js/18.chunk.js:215884:15)
    at BlockService.put (http://localhost:3000/static/js/18.chunk.js:201595:32)
    at IPLDResolver.put (http://localhost:3000/static/js/18.chunk.js:248725:21)
    at async Object.<anonymous> (http://localhost:3000/static/js/18.chunk.js:234774:21)
    at async addRepoAssets (http://localhost:3000/static/js/18.chunk.js:236967:15)
    at async IPFS.<anonymous> (http://localhost:3000/static/js/18.chunk.js:237003:5)
    at async push../node_modules/ipfs/src/core/boot.js.module.exports (http://localhost:3000/static/js/18.chunk.js:234145:7)"

**Comment by oed** [comment]
Thanks @j-mars Yeah I thought the first issue would be solved by the updated version :) 

The new issue seems to be something that changed in an underlaying ipfs dependency. We are seeing it in other places as well. Currently investigating!

**Comment by zachferland** [comment]
@j-mars could you 'npm list ipfs' to see what version of ipfs you have installed, you need 0.40.0 at the moment for 3boxjs, its not explicitly pinned so if you or another dependency are using ipfs anywhere else it may be pulling in a different version

**Comment by j-mars** [comment]
@zachferland npm list ipfs returns:
`└─┬ 3box@1.18.1
  └── ipfs@0.40.0 
`

**Comment by oed** [comment]
Looks like this is an upstream issue in ipfs/ipld: https://github.com/ipfs/js-ipfs/issues/2998

**Comment by j-mars** [comment]
For anyone having this problem, the quick n' dirty workaround based on what you found @oed is to add
`  
"resolutions": {
    "ipld": "0.25.3"
 },
`
To package.json and run yarn/npm install

Confirmed 3box opens now.

**Comment by PfanP** [comment]
Is this issue resolved?

**Comment by PfanP** [comment]
I'm still getting errors with walletconnect
