### ISSUE TITLE
Thread name creation contains [object Object] string.

### ISSUE THREAD

**Issue by deiu** [3box/3box-js#779]
Hi,

Playing with threads I noticed that when joining a thread, the `threadName` value looks a bit odd -- i.e.  "3box.thread.MyFollowing.**[object Object]**". :)

```js
const followingList = await Box.getThread('MyFollowing', 'followingList', myEthAddr, true)
const followingThread = await space.joinThread(followingList, { members: true })

console.log(followingThread) // ->
{
  _accessController: {
  ​​  firstModerator: "did:3:bafyreig4uyjeuc2ww3guyiibwohyk52lrf7a4dixm7762mtx7gnieaxqga"
  ​  ​members: true
  ​​  threadName: "3box.thread.MyFollowing.[object Object]"
  ​​  type: "thread-access"
  },
  ...
}
```

I'm currently using the bundle lib from `https://unpkg.com/3box/dist/3box.js`.

**Comment by oed** [comment]
Thanks for reporting @deiu! Did this start happening recently with the new 3box-js release maybe? Definitely looks like a bug.
@zachferland would you mind having a quick look at this?

**Comment by zachferland** [comment]
@deiu looks like you are passing followingList which is an object into joinThread as the threadName, threadName should be string!

but we should also throw an error in this case to give more feedback vs object getting coerced into string

getThread will just return  values in thread, not instance of a thread

**Comment by deiu** [comment]
Oh I see, that makes sense now. Thanks!
