### ISSUE TITLE
Update Documentation on website

### ISSUE THREAD

**Issue by x5engine** [3box/3box-js#781]
If you follow the documentation on the website 

here https://docs.3box.io/build/web-apps/messaging/persistent-threads#4-view-posts
and here
https://docs.3box.io/api/messaging#thread-getposts

When you are trying to get the post with a limit you get an error!

Documenation says
`        const posts = await thread.getPosts(20)`
when actually you need 
`        const posts = await thread.getPosts({ limit: 20})`

![image](https://user-images.githubusercontent.com/12363020/80772647-f1dd3880-8b46-11ea-80e7-9e8fc15600b0.png)

**Comment by x5engine** [comment]
Also, the links on https://docs.3box.io/api/messaging#thread-getposts are not redirecting to the paragraph when you click them.

**Comment by oed** [comment]
Thanks for reporting this @x5engine We are going to try to fix this as soon as possible!

**Comment by oed** [comment]
Thanks for pointing out where the issues where. Should be updated now!

**Comment by x5engine** [comment]
You are welcome guys :)
