### ISSUE TITLE
3id-connect with ethereum provider or authprovider

### ISSUE THREAD

**Issue by zachferland** [3box/3box-js#784]
Needs to continue to consume and eth (or authprovider), along with 3id-provider (3id-connect)

3id-connect will take this provider now

**Comment by oed** [comment]
3box should be able to detect what type of provider you're using and use the correct authprovider (if possible)

**Comment by zachferland** [comment]
its going to take any eth provider still (not in a auth provider interface) OR any auth provider implemented how you want
