### ISSUE TITLE
Build.js file missing in example

### ISSUE THREAD

**Issue by mikedeshazer** [3box/3box-js#864]
**Describe the bug**
In the this file: https://github.com/3box/3box-js/blob/develop/example/index.html, there is no build.js and the dist directory does not exist.

**To Reproduce**
Clone repo and try to run the example. It won't work because the JS files are missing.

**Expected behavior**
JS files should be present and in correct directoru

Affects all browsers.

**Comment by oed** [comment]
Please see the readme for how to run the example: https://github.com/3box/3box-js#example

**Comment by mikedeshazer** [comment]
Created pull request to help other developers who might not read the entire README before testing the examples folder https://github.com/3box/3box-js/pull/865
