### ISSUE TITLE
'Persistent' confidential threads are not persistent

### ISSUE THREAD

**Issue by drwasho** [3box/3box-js#876]
### Describe the bug
Persistent confidential thread do not appear to be persistent as the thread and its posts disappear after the next session.

#### Step 1. Create the persistent confidential thread
```js
    // Create and fetch the listings in the shopping cart
    const shoppingCart = await space.joinThread('demo-shoppingCart', {
      firstModerator: userMod,
      members: true,
      ghost: false,
      confidential: true,
    });
    this.setState ({ shoppingCart }, () => this.getShoppingCartThread());
```

The above code has also been tested in the following variation:

```js
    // Create and fetch the listings in the shopping cart
    const shoppingCart = await space.createConfidentialThread('demo-shoppingCart'});
    this.setState ({ shoppingCart }, () => this.getShoppingCartThread());
```

#### Step 2. Fetch the shopping cart items and add them to state (update if it changes)

```js
   // getShoppingCartThread => Fetch the cart items in a user's store
  async getShoppingCartThread() {
    if (!this.state.shoppingCart) {
      console.error("shoppingCart thread not in react state");
      return;
    }

    // Fetch the cart items and add them to state
    const cartItems = await this.state.shoppingCart.getPosts();
    this.setState({ cartItems });

    // Update the shopping cart when new items are added
    await this.state.shoppingCart.onUpdate(async () => {
      const cartItems = await this.state.shoppingCart.getPosts();
      this.setState({ cartItems });
    });
  }
```

#### Step 3. Add item to cart

```js
  addToCart = async (_DoThis) => {
    const cartItem = this.props.post;
    console.log(cartItem);
    await this.props.shoppingCart.post(cartItem);
    this.props.getShoppingCartThread();
    console.log(this.props.cartItems);
  };
```

By this step you should be able to check (with react dev tools) if the thread exists and if the item you added to the thread (i.e. the post) is there too. In my test with the code supplied, both the thread and the post were clearly there.

#### Step 4. Refresh the browser (start a new session)

After starting a new session, both the thread and of course the posts are gone.

#### Expected behavior
- We expect to see that persistent confidential threads and their content should persist across multiple sessions
- I tried the exact same code only using a non-confidential thread (code below), and both the thread and posts persisted across multiple sessions, which suggests that it is unlikely my code is at fault:

```js
    // Create and fetch the listings in the shopping cart
    const shoppingCart = await space.joinThread('demo-shoppingCart-public', {
      firstModerator: userMod,
      members: true,
      ghost: false,
      confidential: false,
    });
    this.setState ({ shoppingCart }, () => this.getShoppingCartThread());
```

I'm not an expert dev or anything and I'm mostly hacking around, but if you guys could check this out and confirm or correct what I've reported, I'd appreciate it.

**Comment by zachferland** [comment]
thanks @drwasho for the detailed bug report!

can you try the following, create thread with ```const thread = await space.createConfidentialThread('myConfThread')``` as you have, then you can get the thread address by ```thread.address```, lastly you can rejoin the same thread by ```await space.joinThreadByAddress(address)```

Looks like you may have been creating a new confidential thread each time. Public threads will reference the same thread just by the thread's options, but a confidential thread creates a new key each time and will create a new thread. You can also pass this key as an option to get the same thread, but its easiest to use the address instead (and that encodes all the same info to uniquely reference it)

**Comment by drwasho** [comment]
@zachferland sorry for taking so long to get back to this, but just confirming that it works perfectly!
