### ISSUE TITLE
Result paging from space.private.all?

### ISSUE THREAD

**Issue by jeffkhull** [3box/3box-js#898]
Hi all,

Super excited about 3Box.  For scaling spaces to a large number of documents, is there a way to:

1. Search document by date modified?
2. Page through results?

My basic plan is to keep search indexes sync'd locally in IndexedDB.  I will keep a "date last sync'd" and when the app starts up, I would ideally get just the docs updated since the sync'd date and rebuild the indexes to enable local text search.

I hope this issue isn't a duplicate of an existing.  I wasn't able to find a corresponding issue or discussion in Discord.

**Comment by oed** [comment]
Currently the way 3Box works (really OrbitDB which 3box uses under the hood) is that when you sync a DB you sync all of it's history. This means that all of the entires are loaded into memory. In this case paging would only be a syntactic sugar for developers and not actually load the DB entries partly.

Hope that clarifies things a bit!

**Comment by jeffkhull** [comment]
Makes sense, thanks for the explanation!
