### ISSUE TITLE
Error: "Key not found in database [/...]"

### ISSUE THREAD

**Issue by miguelmota** [3box/3box-js#904]
**Describe the bug**
Error `Key not found in database [/AFYBEIGXHOI4VKIBLJRGDP3K7HGEMT7PET3C35TSNV337PCMDYLI6GPEQY]` when trying to open box. Any help is appreciated. Thanks in advance

![Screenshot from 2020-09-01 10-59-52](https://user-images.githubusercontent.com/168240/91889637-fc1d5980-ec42-11ea-989c-c00570df94d6.png)

**To Reproduce**
```js
import Box from '3box'
import Provider from 'truffle-privatekey-provider'

// ...
const provider = new Provider(privateKey, rpcUrl)
const box = await Box.openBox(publicAddress, provider)
```

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: tested on Linux
 - Browser: tested on Firefox and Chrome
 - Version: latest

**Additional context**
```json
    "3box": "1.21.0",
```

**Comment by zachferland** [comment]
thanks @miguelmota, can you try clearing your cache in your app and for https://cache.3box.io/? and see if this still happens

**Comment by miguelmota** [comment]
tried it on a Chrome Incognito window and received a different error: `"The user denied permission to access the database.`

![Screenshot from 2020-09-01 15-26-47](https://user-images.githubusercontent.com/168240/91912299-ac9d5480-ec67-11ea-8a62-6c3f3b7a9bbb.png)

**Comment by miguelmota** [comment]
This used to work a few months ago with the same code, if that helps

**Comment by zachferland** [comment]
I dont believe all the web apis we need (ipfs and orbitdb) are available for it work incognito mode, ill have to try again. 

But typically this error has been occurring when localstorage/indexeddb is cleared in cache.3box.io but not in the application, which is unlikely. I have seen it otherwise, but clearing application storage should remove it either way.

**Comment by miguelmota** [comment]
I tried clearing all the storage in Chrome non-incognito by going to devtools -> Application -> clear storage, and made sure all the different storage types were empty but received this different error now after trying the same code: `Must provide a location for the database`

![Screenshot from 2020-09-01 18-20-21](https://user-images.githubusercontent.com/168240/91921309-0a3d9b00-ec80-11ea-9d9f-c90870e7fbaa.png)

**Comment by zachferland** [comment]
I believe i have seen this from some sub dependency mismatches, worth trying removing node_modules and installing again 

I can try to see if I can replicate as well

**Comment by Jshanks21** [comment]
> thanks @miguelmota, can you try clearing your cache in your app and for https://cache.3box.io/? and see if this still happens

Thank you for this @zachferland! I started getting the "Key not found in database [/...]" error a couple days ago, but this solved it for me.

**Comment by zachferland** [comment]
Closing issue, the last release also included a fix for 'key not found' errors, can open new issue if any continuing issues
