### ISSUE TITLE
can't install web3

### ISSUE THREAD

**Issue by vinhyenvodoi98** [3box/3box-js#957]
**Describe the bug**
fail when install 3box 
```
ended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/hugomrdias/pull-ws.git
```
![image](https://user-images.githubusercontent.com/33363513/109788172-989bd500-7c41-11eb-9018-e2db2df6ddcc.png)

look like the reason is hugomrdias delete pull-ws repo

**Comment by adamsoffer** [comment]
@vinhyenvodoi98 how'd you get around this issue?

**Comment by vinhyenvodoi98** [comment]
@adamsoffer I installed it before so I have 3box in node_module and I copy it from project to project. However it is not a good solution so I'm still waiting for 3box to come up with their solution.

**Comment by adamsoffer** [comment]
Hey @vinhyenvodoi98 - I was able to get around the issue by adding the following yarn resolution to my `package.json`:

```json
"resolutions": {
  "pull-ws": "3.3.2"
}

**Comment by vinhyenvodoi98** [comment]
@adamsoffer awesome i definitely try it
